/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	ChangeInterviewFormatRequest,
	ChangeInterviewStatusRequest,
	GetInterviewsParams,
	InterviewCreated,
	InterviewFormatChanged,
	InterviewProjection,
	InterviewStatusChanged,
	ProblemDetails,
	ScheduleInterviewRequest,
	SliceResponseOfInterviewProjection,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Get interviews
 */
export const getInterviews = (
	params?: GetInterviewsParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfInterviewProjection>(
		{ url: `/api/interviews`, method: "GET", params, signal },
		options,
	);
};

export const getGetInterviewsMutationKey = () => ["getInterviews"] as const;

export const getGetInterviewsMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getInterviews>>,
		TError,
		GetInterviewsMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getInterviews>>,
	TError,
	GetInterviewsMutationVariables,
	TContext
> => {
	const mutationKey = getGetInterviewsMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getInterviews>>,
		GetInterviewsMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getInterviews(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetInterviewsMutationResult = NonNullable<Awaited<ReturnType<typeof getInterviews>>>;

export type GetInterviewsMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetInterviewsMutationVariables = { params?: GetInterviewsParams };

/**
 * @summary Get interviews
 */
export const useGetInterviews = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getInterviews>>,
			TError,
			GetInterviewsMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getInterviews>>,
	TError,
	GetInterviewsMutationVariables,
	TContext
> => {
	return useMutation(getGetInterviewsMutationOptions(options), queryClient);
};
/**
 * @summary Get interview
 */
export const getInterview = (
	interviewId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<InterviewProjection>(
		{ url: `/api/interviews/${interviewId}`, method: "GET", signal },
		options,
	);
};

export const getGetInterviewMutationKey = () => ["getInterview"] as const;

export const getGetInterviewMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getInterview>>,
		TError,
		GetInterviewMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getInterview>>,
	TError,
	GetInterviewMutationVariables,
	TContext
> => {
	const mutationKey = getGetInterviewMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getInterview>>,
		GetInterviewMutationVariables
	> = (props) => {
		const { interviewId } = props ?? {};

		return getInterview(interviewId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetInterviewMutationResult = NonNullable<Awaited<ReturnType<typeof getInterview>>>;

export type GetInterviewMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetInterviewMutationVariables = { interviewId: string };

/**
 * @summary Get interview
 */
export const useGetInterview = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getInterview>>,
			TError,
			GetInterviewMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getInterview>>,
	TError,
	GetInterviewMutationVariables,
	TContext
> => {
	return useMutation(getGetInterviewMutationOptions(options), queryClient);
};
/**
 * @summary Schedule interview
 */
export const scheduleInterview = (
	scheduleInterviewRequest: BodyType<ScheduleInterviewRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<InterviewCreated>(
		{
			url: `/api/interviews/schedule`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: scheduleInterviewRequest,
			signal,
		},
		options,
	);
};

export const getScheduleInterviewQueryKey = (
	scheduleInterviewRequest?: BodyType<ScheduleInterviewRequest>,
) => {
	return ["POST", `/api/interviews/schedule`, scheduleInterviewRequest] as const;
};

export const getScheduleInterviewQueryOptions = <
	TData = Awaited<ReturnType<typeof scheduleInterview>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	scheduleInterviewRequest: BodyType<ScheduleInterviewRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleInterview>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getScheduleInterviewQueryKey(scheduleInterviewRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleInterview>>> = ({ signal }) =>
		scheduleInterview(scheduleInterviewRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof scheduleInterview>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ScheduleInterviewQueryResult = NonNullable<
	Awaited<ReturnType<typeof scheduleInterview>>
>;
export type ScheduleInterviewQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useScheduleInterview<
	TData = Awaited<ReturnType<typeof scheduleInterview>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	scheduleInterviewRequest: BodyType<ScheduleInterviewRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleInterview>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof scheduleInterview>>,
					TError,
					Awaited<ReturnType<typeof scheduleInterview>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleInterview<
	TData = Awaited<ReturnType<typeof scheduleInterview>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	scheduleInterviewRequest: BodyType<ScheduleInterviewRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleInterview>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof scheduleInterview>>,
					TError,
					Awaited<ReturnType<typeof scheduleInterview>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleInterview<
	TData = Awaited<ReturnType<typeof scheduleInterview>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	scheduleInterviewRequest: BodyType<ScheduleInterviewRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleInterview>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Schedule interview
 */

export function useScheduleInterview<
	TData = Awaited<ReturnType<typeof scheduleInterview>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	scheduleInterviewRequest: BodyType<ScheduleInterviewRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleInterview>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getScheduleInterviewQueryOptions(scheduleInterviewRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Change format
 */
export const changeInterviewFormat = (
	interviewId: string,
	changeInterviewFormatRequest: BodyType<ChangeInterviewFormatRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<InterviewFormatChanged>(
		{
			url: `/api/interviews/${interviewId}/format`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changeInterviewFormatRequest,
			signal,
		},
		options,
	);
};

export const getChangeInterviewFormatQueryKey = (
	interviewId: string,
	changeInterviewFormatRequest?: BodyType<ChangeInterviewFormatRequest>,
) => {
	return ["PUT", `/api/interviews/${interviewId}/format`, changeInterviewFormatRequest] as const;
};

export const getChangeInterviewFormatQueryOptions = <
	TData = Awaited<ReturnType<typeof changeInterviewFormat>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewFormatRequest: BodyType<ChangeInterviewFormatRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewFormat>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getChangeInterviewFormatQueryKey(interviewId, changeInterviewFormatRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof changeInterviewFormat>>> = ({ signal }) =>
		changeInterviewFormat(interviewId, changeInterviewFormatRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: interviewId !== null && interviewId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof changeInterviewFormat>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ChangeInterviewFormatQueryResult = NonNullable<
	Awaited<ReturnType<typeof changeInterviewFormat>>
>;
export type ChangeInterviewFormatQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useChangeInterviewFormat<
	TData = Awaited<ReturnType<typeof changeInterviewFormat>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewFormatRequest: BodyType<ChangeInterviewFormatRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewFormat>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeInterviewFormat>>,
					TError,
					Awaited<ReturnType<typeof changeInterviewFormat>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeInterviewFormat<
	TData = Awaited<ReturnType<typeof changeInterviewFormat>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewFormatRequest: BodyType<ChangeInterviewFormatRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewFormat>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeInterviewFormat>>,
					TError,
					Awaited<ReturnType<typeof changeInterviewFormat>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeInterviewFormat<
	TData = Awaited<ReturnType<typeof changeInterviewFormat>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewFormatRequest: BodyType<ChangeInterviewFormatRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewFormat>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change format
 */

export function useChangeInterviewFormat<
	TData = Awaited<ReturnType<typeof changeInterviewFormat>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewFormatRequest: BodyType<ChangeInterviewFormatRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewFormat>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getChangeInterviewFormatQueryOptions(
		interviewId,
		changeInterviewFormatRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Change status
 */
export const changeInterviewStatus = (
	interviewId: string,
	changeInterviewStatusRequest: BodyType<ChangeInterviewStatusRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<InterviewStatusChanged>(
		{
			url: `/api/interviews/${interviewId}/status`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changeInterviewStatusRequest,
			signal,
		},
		options,
	);
};

export const getChangeInterviewStatusQueryKey = (
	interviewId: string,
	changeInterviewStatusRequest?: BodyType<ChangeInterviewStatusRequest>,
) => {
	return ["PUT", `/api/interviews/${interviewId}/status`, changeInterviewStatusRequest] as const;
};

export const getChangeInterviewStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof changeInterviewStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewStatusRequest: BodyType<ChangeInterviewStatusRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getChangeInterviewStatusQueryKey(interviewId, changeInterviewStatusRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof changeInterviewStatus>>> = ({ signal }) =>
		changeInterviewStatus(interviewId, changeInterviewStatusRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: interviewId !== null && interviewId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof changeInterviewStatus>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ChangeInterviewStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof changeInterviewStatus>>
>;
export type ChangeInterviewStatusQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useChangeInterviewStatus<
	TData = Awaited<ReturnType<typeof changeInterviewStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewStatusRequest: BodyType<ChangeInterviewStatusRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewStatus>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeInterviewStatus>>,
					TError,
					Awaited<ReturnType<typeof changeInterviewStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeInterviewStatus<
	TData = Awaited<ReturnType<typeof changeInterviewStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewStatusRequest: BodyType<ChangeInterviewStatusRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewStatus>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeInterviewStatus>>,
					TError,
					Awaited<ReturnType<typeof changeInterviewStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeInterviewStatus<
	TData = Awaited<ReturnType<typeof changeInterviewStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewStatusRequest: BodyType<ChangeInterviewStatusRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change status
 */

export function useChangeInterviewStatus<
	TData = Awaited<ReturnType<typeof changeInterviewStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	interviewId: string,
	changeInterviewStatusRequest: BodyType<ChangeInterviewStatusRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeInterviewStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getChangeInterviewStatusQueryOptions(
		interviewId,
		changeInterviewStatusRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
