FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Directory.Packages.props .

COPY src/HrAgencySystem.Files/HrAgencySystem.Files.csproj HrAgencySystem.Files/
COPY src/services/HrAgencySystem.FileService.Contracts/HrAgencySystem.FileService.Contracts.csproj services/HrAgencySystem.FileService.Contracts/
COPY src/services/HrAgencySystem.FileService/HrAgencySystem.FileService.csproj services/HrAgencySystem.FileService/

RUN dotnet restore services/HrAgencySystem.FileService/HrAgencySystem.FileService.csproj

COPY src .

RUN dotnet publish services/HrAgencySystem.FileService/HrAgencySystem.FileService.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish \
    /p:UseAppHost=false

FROM runtime AS final

WORKDIR /app

COPY --from=build --chown=app:app /app/publish .

USER app

ENTRYPOINT ["dotnet", "HrAgencySystem.FileService.dll"]
