/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CreateUserRequest,
	GetUsersParams,
	ProblemDetails,
	SliceResponseOfUserProjection,
	UserCreated,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create user
 */
export const createUser = (
	createUserRequest: BodyType<CreateUserRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserCreated>(
		{
			url: `/api/users`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createUserRequest,
			signal,
		},
		options,
	);
};

export const getCreateUserQueryKey = (createUserRequest?: BodyType<CreateUserRequest>) => {
	return ["POST", `/api/users`, createUserRequest] as const;
};

export const getCreateUserQueryOptions = <
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCreateUserQueryKey(createUserRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof createUser>>> = ({ signal }) =>
		createUser(createUserRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof createUser>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateUserQueryResult = NonNullable<Awaited<ReturnType<typeof createUser>>>;
export type CreateUserQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof createUser>>,
					TError,
					Awaited<ReturnType<typeof createUser>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof createUser>>,
					TError,
					Awaited<ReturnType<typeof createUser>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create user
 */

export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCreateUserQueryOptions(createUserRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get users
 */
export const getUsers = (
	params: GetUsersParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfUserProjection>(
		{ url: `/api/users`, method: "GET", params, signal },
		options,
	);
};

export const getGetUsersMutationKey = () => ["getUsers"] as const;

export const getGetUsersMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		GetUsersMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getUsers>>,
	TError,
	GetUsersMutationVariables,
	TContext
> => {
	const mutationKey = getGetUsersMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getUsers(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetUsersMutationResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;

export type GetUsersMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetUsersMutationVariables = { params: GetUsersParams };

/**
 * @summary Get users
 */
export const useGetUsers = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getUsers>>,
			TError,
			GetUsersMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getUsers>>,
	TError,
	GetUsersMutationVariables,
	TContext
> => {
	return useMutation(getGetUsersMutationOptions(options), queryClient);
};
