/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	ChangePasswordRequest,
	ChangeUserRoleRequest,
	CreateUserRequest,
	GetUsersParams,
	MyProfileResponse,
	ProblemDetails,
	RoleChanged,
	SliceResponseOfUserProjection,
	UpdateOwnProfileRequest,
	UpdateUserRequest,
	UploadOwnAvatarBody,
	UploadUserAvatarBody,
	UserAvatarChanged,
	UserAvatarRef,
	UserAvatarRemoved,
	UserCreated,
	UserProjection,
	UserUpdated,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator.ts";
import { customInstance } from "../../mutator.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create user
 */
export const createUser = (
	createUserRequest: BodyType<CreateUserRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserCreated>(
		{
			url: `/api/users`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createUserRequest,
			signal,
		},
		options,
	);
};

export const getCreateUserQueryKey = (createUserRequest?: BodyType<CreateUserRequest>) => {
	return ["POST", `/api/users`, createUserRequest] as const;
};

export const getCreateUserQueryOptions = <
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCreateUserQueryKey(createUserRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof createUser>>> = ({ signal }) =>
		createUser(createUserRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof createUser>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateUserQueryResult = NonNullable<Awaited<ReturnType<typeof createUser>>>;
export type CreateUserQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof createUser>>,
					TError,
					Awaited<ReturnType<typeof createUser>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof createUser>>,
					TError,
					Awaited<ReturnType<typeof createUser>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create user
 */

export function useCreateUser<
	TData = Awaited<ReturnType<typeof createUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createUserRequest: BodyType<CreateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCreateUserQueryOptions(createUserRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get users
 */
export const getUsers = (
	params: GetUsersParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfUserProjection>(
		{ url: `/api/users`, method: "GET", params, signal },
		options,
	);
};

export const getGetUsersMutationKey = () => ["getUsers"] as const;

export const getGetUsersMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		GetUsersMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getUsers>>,
	TError,
	GetUsersMutationVariables,
	TContext
> => {
	const mutationKey = getGetUsersMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getUsers(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetUsersMutationResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;

export type GetUsersMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetUsersMutationVariables = { params: GetUsersParams };

/**
 * @summary Get users
 */
export const useGetUsers = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getUsers>>,
			TError,
			GetUsersMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getUsers>>,
	TError,
	GetUsersMutationVariables,
	TContext
> => {
	return useMutation(getGetUsersMutationOptions(options), queryClient);
};
/**
 * @summary Update user
 */
export const updateUser = (
	userId: string,
	updateUserRequest: BodyType<UpdateUserRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserUpdated>(
		{
			url: `/api/users/${userId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateUserRequest,
			signal,
		},
		options,
	);
};

export const getUpdateUserQueryKey = (
	userId: string,
	updateUserRequest?: BodyType<UpdateUserRequest>,
) => {
	return ["PUT", `/api/users/${userId}`, updateUserRequest] as const;
};

export const getUpdateUserQueryOptions = <
	TData = Awaited<ReturnType<typeof updateUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	updateUserRequest: BodyType<UpdateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUpdateUserQueryKey(userId, updateUserRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateUser>>> = ({ signal }) =>
		updateUser(userId, updateUserRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: userId !== null && userId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof updateUser>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UpdateUserQueryResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type UpdateUserQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateUser<
	TData = Awaited<ReturnType<typeof updateUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	updateUserRequest: BodyType<UpdateUserRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUser>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateUser>>,
					TError,
					Awaited<ReturnType<typeof updateUser>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateUser<
	TData = Awaited<ReturnType<typeof updateUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	updateUserRequest: BodyType<UpdateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUser>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateUser>>,
					TError,
					Awaited<ReturnType<typeof updateUser>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateUser<
	TData = Awaited<ReturnType<typeof updateUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	updateUserRequest: BodyType<UpdateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update user
 */

export function useUpdateUser<
	TData = Awaited<ReturnType<typeof updateUser>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	updateUserRequest: BodyType<UpdateUserRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUser>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateUserQueryOptions(userId, updateUserRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get user
 */
export const getUser = (
	userId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserProjection>(
		{ url: `/api/users/${userId}`, method: "GET", signal },
		options,
	);
};

export const getGetUserMutationKey = () => ["getUser"] as const;

export const getGetUserMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getUser>>,
		TError,
		GetUserMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getUser>>,
	TError,
	GetUserMutationVariables,
	TContext
> => {
	const mutationKey = getGetUserMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getUser>>,
		GetUserMutationVariables
	> = (props) => {
		const { userId } = props ?? {};

		return getUser(userId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetUserMutationResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;

export type GetUserMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetUserMutationVariables = { userId: string };

/**
 * @summary Get user
 */
export const useGetUser = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getUser>>,
			TError,
			GetUserMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getUser>>,
	TError,
	GetUserMutationVariables,
	TContext
> => {
	return useMutation(getGetUserMutationOptions(options), queryClient);
};
/**
 * @summary Change user role
 */
export const changeUserRole = (
	userId: string,
	changeUserRoleRequest: BodyType<ChangeUserRoleRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<RoleChanged>(
		{
			url: `/api/users/${userId}/role`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changeUserRoleRequest,
			signal,
		},
		options,
	);
};

export const getChangeUserRoleQueryKey = (
	userId: string,
	changeUserRoleRequest?: BodyType<ChangeUserRoleRequest>,
) => {
	return ["PUT", `/api/users/${userId}/role`, changeUserRoleRequest] as const;
};

export const getChangeUserRoleQueryOptions = <
	TData = Awaited<ReturnType<typeof changeUserRole>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeUserRoleRequest: BodyType<ChangeUserRoleRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeUserRole>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getChangeUserRoleQueryKey(userId, changeUserRoleRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof changeUserRole>>> = ({ signal }) =>
		changeUserRole(userId, changeUserRoleRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: userId !== null && userId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof changeUserRole>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ChangeUserRoleQueryResult = NonNullable<Awaited<ReturnType<typeof changeUserRole>>>;
export type ChangeUserRoleQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useChangeUserRole<
	TData = Awaited<ReturnType<typeof changeUserRole>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeUserRoleRequest: BodyType<ChangeUserRoleRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeUserRole>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeUserRole>>,
					TError,
					Awaited<ReturnType<typeof changeUserRole>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeUserRole<
	TData = Awaited<ReturnType<typeof changeUserRole>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeUserRoleRequest: BodyType<ChangeUserRoleRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeUserRole>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeUserRole>>,
					TError,
					Awaited<ReturnType<typeof changeUserRole>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeUserRole<
	TData = Awaited<ReturnType<typeof changeUserRole>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeUserRoleRequest: BodyType<ChangeUserRoleRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeUserRole>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change user role
 */

export function useChangeUserRole<
	TData = Awaited<ReturnType<typeof changeUserRole>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeUserRoleRequest: BodyType<ChangeUserRoleRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeUserRole>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getChangeUserRoleQueryOptions(userId, changeUserRoleRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Change own password
 */
export const changeOwnPassword = (
	changePasswordRequest: BodyType<ChangePasswordRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/users/me/password`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changePasswordRequest,
			signal,
		},
		options,
	);
};

export const getChangeOwnPasswordQueryKey = (
	changePasswordRequest?: BodyType<ChangePasswordRequest>,
) => {
	return ["PUT", `/api/users/me/password`, changePasswordRequest] as const;
};

export const getChangeOwnPasswordQueryOptions = <
	TData = Awaited<ReturnType<typeof changeOwnPassword>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	changePasswordRequest: BodyType<ChangePasswordRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeOwnPassword>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getChangeOwnPasswordQueryKey(changePasswordRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof changeOwnPassword>>> = ({ signal }) =>
		changeOwnPassword(changePasswordRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof changeOwnPassword>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChangeOwnPasswordQueryResult = NonNullable<
	Awaited<ReturnType<typeof changeOwnPassword>>
>;
export type ChangeOwnPasswordQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useChangeOwnPassword<
	TData = Awaited<ReturnType<typeof changeOwnPassword>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	changePasswordRequest: BodyType<ChangePasswordRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeOwnPassword>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeOwnPassword>>,
					TError,
					Awaited<ReturnType<typeof changeOwnPassword>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeOwnPassword<
	TData = Awaited<ReturnType<typeof changeOwnPassword>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	changePasswordRequest: BodyType<ChangePasswordRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeOwnPassword>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeOwnPassword>>,
					TError,
					Awaited<ReturnType<typeof changeOwnPassword>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeOwnPassword<
	TData = Awaited<ReturnType<typeof changeOwnPassword>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	changePasswordRequest: BodyType<ChangePasswordRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeOwnPassword>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change own password
 */

export function useChangeOwnPassword<
	TData = Awaited<ReturnType<typeof changeOwnPassword>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	changePasswordRequest: BodyType<ChangePasswordRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changeOwnPassword>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getChangeOwnPasswordQueryOptions(changePasswordRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get own profile
 */
export const getOwnProfile = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<MyProfileResponse>(
		{ url: `/api/users/me`, method: "GET", signal },
		options,
	);
};

export const getGetOwnProfileMutationKey = () => ["getOwnProfile"] as const;

export const getGetOwnProfileMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof getOwnProfile>>, TError, void, TContext>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof getOwnProfile>>, TError, void, TContext> => {
	const mutationKey = getGetOwnProfileMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof getOwnProfile>>, void> = () => {
		return getOwnProfile(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetOwnProfileMutationResult = NonNullable<Awaited<ReturnType<typeof getOwnProfile>>>;

export type GetOwnProfileMutationError = ErrorType<BadRequestDetails | ProblemDetails>;

/**
 * @summary Get own profile
 */
export const useGetOwnProfile = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getOwnProfile>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof getOwnProfile>>, TError, void, TContext> => {
	return useMutation(getGetOwnProfileMutationOptions(options), queryClient);
};
/**
 * @summary Update own profile
 */
export const updateOwnProfile = (
	updateOwnProfileRequest: BodyType<UpdateOwnProfileRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserUpdated>(
		{
			url: `/api/users/me`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateOwnProfileRequest,
			signal,
		},
		options,
	);
};

export const getUpdateOwnProfileQueryKey = (
	updateOwnProfileRequest?: BodyType<UpdateOwnProfileRequest>,
) => {
	return ["PUT", `/api/users/me`, updateOwnProfileRequest] as const;
};

export const getUpdateOwnProfileQueryOptions = <
	TData = Awaited<ReturnType<typeof updateOwnProfile>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	updateOwnProfileRequest: BodyType<UpdateOwnProfileRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOwnProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUpdateOwnProfileQueryKey(updateOwnProfileRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateOwnProfile>>> = ({ signal }) =>
		updateOwnProfile(updateOwnProfileRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof updateOwnProfile>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UpdateOwnProfileQueryResult = NonNullable<Awaited<ReturnType<typeof updateOwnProfile>>>;
export type UpdateOwnProfileQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateOwnProfile<
	TData = Awaited<ReturnType<typeof updateOwnProfile>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	updateOwnProfileRequest: BodyType<UpdateOwnProfileRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOwnProfile>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateOwnProfile>>,
					TError,
					Awaited<ReturnType<typeof updateOwnProfile>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateOwnProfile<
	TData = Awaited<ReturnType<typeof updateOwnProfile>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	updateOwnProfileRequest: BodyType<UpdateOwnProfileRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOwnProfile>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateOwnProfile>>,
					TError,
					Awaited<ReturnType<typeof updateOwnProfile>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateOwnProfile<
	TData = Awaited<ReturnType<typeof updateOwnProfile>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	updateOwnProfileRequest: BodyType<UpdateOwnProfileRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOwnProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update own profile
 */

export function useUpdateOwnProfile<
	TData = Awaited<ReturnType<typeof updateOwnProfile>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	updateOwnProfileRequest: BodyType<UpdateOwnProfileRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOwnProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateOwnProfileQueryOptions(updateOwnProfileRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Upload own profile picture
 */
export const uploadOwnAvatar = (
	uploadOwnAvatarBody: BodyType<UploadOwnAvatarBody>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	const formData = new FormData();
	formData.append(`file`, uploadOwnAvatarBody.file);

	return customInstance<UserAvatarChanged>(
		{
			url: `/api/users/me/avatar`,
			method: "POST",
			headers: { "Content-Type": "multipart/form-data" },
			data: formData,
			signal,
		},
		options,
	);
};

export const getUploadOwnAvatarQueryKey = (uploadOwnAvatarBody?: BodyType<UploadOwnAvatarBody>) => {
	return ["POST", `/api/users/me/avatar`, uploadOwnAvatarBody] as const;
};

export const getUploadOwnAvatarQueryOptions = <
	TData = Awaited<ReturnType<typeof uploadOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	uploadOwnAvatarBody: BodyType<UploadOwnAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadOwnAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUploadOwnAvatarQueryKey(uploadOwnAvatarBody);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof uploadOwnAvatar>>> = ({ signal }) =>
		uploadOwnAvatar(uploadOwnAvatarBody, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof uploadOwnAvatar>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UploadOwnAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof uploadOwnAvatar>>>;
export type UploadOwnAvatarQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUploadOwnAvatar<
	TData = Awaited<ReturnType<typeof uploadOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	uploadOwnAvatarBody: BodyType<UploadOwnAvatarBody>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadOwnAvatar>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof uploadOwnAvatar>>,
					TError,
					Awaited<ReturnType<typeof uploadOwnAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUploadOwnAvatar<
	TData = Awaited<ReturnType<typeof uploadOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	uploadOwnAvatarBody: BodyType<UploadOwnAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadOwnAvatar>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof uploadOwnAvatar>>,
					TError,
					Awaited<ReturnType<typeof uploadOwnAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUploadOwnAvatar<
	TData = Awaited<ReturnType<typeof uploadOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	uploadOwnAvatarBody: BodyType<UploadOwnAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadOwnAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Upload own profile picture
 */

export function useUploadOwnAvatar<
	TData = Awaited<ReturnType<typeof uploadOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	uploadOwnAvatarBody: BodyType<UploadOwnAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadOwnAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUploadOwnAvatarQueryOptions(uploadOwnAvatarBody, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Download own profile picture
 */
export const downloadOwnAvatar = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>({ url: `/api/users/me/avatar`, method: "GET", signal }, options);
};

export const getDownloadOwnAvatarMutationKey = () => ["downloadOwnAvatar"] as const;

export const getDownloadOwnAvatarMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof downloadOwnAvatar>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof downloadOwnAvatar>>, TError, void, TContext> => {
	const mutationKey = getDownloadOwnAvatarMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof downloadOwnAvatar>>, void> = () => {
		return downloadOwnAvatar(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DownloadOwnAvatarMutationResult = NonNullable<
	Awaited<ReturnType<typeof downloadOwnAvatar>>
>;

export type DownloadOwnAvatarMutationError = ErrorType<BadRequestDetails | ProblemDetails>;

/**
 * @summary Download own profile picture
 */
export const useDownloadOwnAvatar = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof downloadOwnAvatar>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof downloadOwnAvatar>>, TError, void, TContext> => {
	return useMutation(getDownloadOwnAvatarMutationOptions(options), queryClient);
};
/**
 * @summary Remove own profile picture
 */
export const removeOwnAvatar = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserAvatarRemoved>(
		{ url: `/api/users/me/avatar`, method: "DELETE", signal },
		options,
	);
};

export const getRemoveOwnAvatarQueryKey = () => {
	return ["DELETE", `/api/users/me/avatar`] as const;
};

export const getRemoveOwnAvatarQueryOptions = <
	TData = Awaited<ReturnType<typeof removeOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeOwnAvatar>>, TError, TData>>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRemoveOwnAvatarQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof removeOwnAvatar>>> = ({ signal }) =>
		removeOwnAvatar(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof removeOwnAvatar>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RemoveOwnAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof removeOwnAvatar>>>;
export type RemoveOwnAvatarQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useRemoveOwnAvatar<
	TData = Awaited<ReturnType<typeof removeOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeOwnAvatar>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof removeOwnAvatar>>,
					TError,
					Awaited<ReturnType<typeof removeOwnAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveOwnAvatar<
	TData = Awaited<ReturnType<typeof removeOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeOwnAvatar>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof removeOwnAvatar>>,
					TError,
					Awaited<ReturnType<typeof removeOwnAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveOwnAvatar<
	TData = Awaited<ReturnType<typeof removeOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeOwnAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Remove own profile picture
 */

export function useRemoveOwnAvatar<
	TData = Awaited<ReturnType<typeof removeOwnAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeOwnAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getRemoveOwnAvatarQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get the profile pictures in the organization
 */
export const getUserAvatars = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserAvatarRef[]>(
		{ url: `/api/users/avatars`, method: "GET", signal },
		options,
	);
};

export const getGetUserAvatarsMutationKey = () => ["getUserAvatars"] as const;

export const getGetUserAvatarsMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof getUserAvatars>>, TError, void, TContext>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof getUserAvatars>>, TError, void, TContext> => {
	const mutationKey = getGetUserAvatarsMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserAvatars>>, void> = () => {
		return getUserAvatars(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetUserAvatarsMutationResult = NonNullable<Awaited<ReturnType<typeof getUserAvatars>>>;

export type GetUserAvatarsMutationError = ErrorType<BadRequestDetails | ProblemDetails>;

/**
 * @summary Get the profile pictures in the organization
 */
export const useGetUserAvatars = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getUserAvatars>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof getUserAvatars>>, TError, void, TContext> => {
	return useMutation(getGetUserAvatarsMutationOptions(options), queryClient);
};
/**
 * @summary Upload another member's profile picture
 */
export const uploadUserAvatar = (
	userId: string,
	uploadUserAvatarBody: BodyType<UploadUserAvatarBody>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	const formData = new FormData();
	formData.append(`file`, uploadUserAvatarBody.file);

	return customInstance<UserAvatarChanged>(
		{
			url: `/api/users/${userId}/avatar`,
			method: "POST",
			headers: { "Content-Type": "multipart/form-data" },
			data: formData,
			signal,
		},
		options,
	);
};

export const getUploadUserAvatarQueryKey = (
	userId: string,
	uploadUserAvatarBody?: BodyType<UploadUserAvatarBody>,
) => {
	return ["POST", `/api/users/${userId}/avatar`, uploadUserAvatarBody] as const;
};

export const getUploadUserAvatarQueryOptions = <
	TData = Awaited<ReturnType<typeof uploadUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	uploadUserAvatarBody: BodyType<UploadUserAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadUserAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getUploadUserAvatarQueryKey(userId, uploadUserAvatarBody);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof uploadUserAvatar>>> = ({ signal }) =>
		uploadUserAvatar(userId, uploadUserAvatarBody, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: userId !== null && userId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof uploadUserAvatar>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UploadUserAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof uploadUserAvatar>>>;
export type UploadUserAvatarQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUploadUserAvatar<
	TData = Awaited<ReturnType<typeof uploadUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	uploadUserAvatarBody: BodyType<UploadUserAvatarBody>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadUserAvatar>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof uploadUserAvatar>>,
					TError,
					Awaited<ReturnType<typeof uploadUserAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUploadUserAvatar<
	TData = Awaited<ReturnType<typeof uploadUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	uploadUserAvatarBody: BodyType<UploadUserAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadUserAvatar>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof uploadUserAvatar>>,
					TError,
					Awaited<ReturnType<typeof uploadUserAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUploadUserAvatar<
	TData = Awaited<ReturnType<typeof uploadUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	uploadUserAvatarBody: BodyType<UploadUserAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadUserAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Upload another member's profile picture
 */

export function useUploadUserAvatar<
	TData = Awaited<ReturnType<typeof uploadUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	uploadUserAvatarBody: BodyType<UploadUserAvatarBody>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadUserAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUploadUserAvatarQueryOptions(userId, uploadUserAvatarBody, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Download another member's profile picture
 */
export const downloadUserAvatar = (
	userId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{ url: `/api/users/${userId}/avatar`, method: "GET", signal },
		options,
	);
};

export const getDownloadUserAvatarMutationKey = () => ["downloadUserAvatar"] as const;

export const getDownloadUserAvatarMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof downloadUserAvatar>>,
		TError,
		DownloadUserAvatarMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof downloadUserAvatar>>,
	TError,
	DownloadUserAvatarMutationVariables,
	TContext
> => {
	const mutationKey = getDownloadUserAvatarMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof downloadUserAvatar>>,
		DownloadUserAvatarMutationVariables
	> = (props) => {
		const { userId } = props ?? {};

		return downloadUserAvatar(userId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DownloadUserAvatarMutationResult = NonNullable<
	Awaited<ReturnType<typeof downloadUserAvatar>>
>;

export type DownloadUserAvatarMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type DownloadUserAvatarMutationVariables = { userId: string };

/**
 * @summary Download another member's profile picture
 */
export const useDownloadUserAvatar = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof downloadUserAvatar>>,
			TError,
			DownloadUserAvatarMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof downloadUserAvatar>>,
	TError,
	DownloadUserAvatarMutationVariables,
	TContext
> => {
	return useMutation(getDownloadUserAvatarMutationOptions(options), queryClient);
};
/**
 * @summary Remove another member's profile picture
 */
export const removeUserAvatar = (
	userId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UserAvatarRemoved>(
		{ url: `/api/users/${userId}/avatar`, method: "DELETE", signal },
		options,
	);
};

export const getRemoveUserAvatarQueryKey = (userId: string) => {
	return ["DELETE", `/api/users/${userId}/avatar`] as const;
};

export const getRemoveUserAvatarQueryOptions = <
	TData = Awaited<ReturnType<typeof removeUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeUserAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRemoveUserAvatarQueryKey(userId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof removeUserAvatar>>> = ({ signal }) =>
		removeUserAvatar(userId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: userId !== null && userId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof removeUserAvatar>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type RemoveUserAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof removeUserAvatar>>>;
export type RemoveUserAvatarQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useRemoveUserAvatar<
	TData = Awaited<ReturnType<typeof removeUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeUserAvatar>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof removeUserAvatar>>,
					TError,
					Awaited<ReturnType<typeof removeUserAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveUserAvatar<
	TData = Awaited<ReturnType<typeof removeUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeUserAvatar>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof removeUserAvatar>>,
					TError,
					Awaited<ReturnType<typeof removeUserAvatar>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveUserAvatar<
	TData = Awaited<ReturnType<typeof removeUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeUserAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Remove another member's profile picture
 */

export function useRemoveUserAvatar<
	TData = Awaited<ReturnType<typeof removeUserAvatar>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeUserAvatar>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getRemoveUserAvatarQueryOptions(userId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
