<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Marten" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Marten" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HrAgencySystem.PlatformSeeder\HrAgencySystem.PlatformSeeder.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Feeds\HrAgencySystem.Feeds.csproj" />
    <ProjectReference Include="..\HrAgencySystem.SharedKernel\HrAgencySystem.SharedKernel.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Identity\HrAgencySystem.Identity.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Organization\HrAgencySystem.Organization.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Company\HrAgencySystem.Company.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Recruitment\HrAgencySystem.Recruitment.csproj" />
    <ProjectReference Include="..\HrAgencySystem.JobDescription\HrAgencySystem.JobDescription.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Agency\HrAgencySystem.Agency.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Projects\HrAgencySystem.Projects.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Workers\HrAgencySystem.Workers.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Sales\HrAgencySystem.Sales.csproj" />
    <ProjectReference Include="..\HrAgencySystem.LegalEntities\HrAgencySystem.LegalEntities.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Teams\HrAgencySystem.Teams.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Audit\HrAgencySystem.Audit.csproj" />
    <ProjectReference Include="..\EmailTemplates\HrAgencySystem.EmailTemplates.Messaging\HrAgencySystem.EmailTemplates.Messaging.csproj" />
    <ProjectReference Include="..\services\HrAgencySystem.FileService.Contracts\HrAgencySystem.FileService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HrAgencySystem.IntegrationTests" />
  </ItemGroup>
</Project>
