@baseURL = http://localhost:5000

### Login Platform User
# @name login
POST {{baseURL}}/api/auth/login
Content-Type: application/json

{
    "email": "j.smith@hr-agency.com",
    "password": "test123",
    "slug": "hr-agency"
}

###
@token = {{login.response.body.$.token}}

###

### posting 
# @name postOne
GET {{baseURL}}/api/recruitment/job-posting?search=Spring
Authorization: Bearer {{token}}


###
@jobPostId1 = {{postOne.response.body.$.content[0].id}}
###

### posting 
# @name postTwo
GET {{baseURL}}/api/recruitment/job-posting?search=NextJS
Authorization: Bearer {{token}}

###
@jobPostId2 = {{postTwo.response.body.$.content[0].id}}
###

### posting 
# @name postThree
GET {{baseURL}}/api/recruitment/job-posting?search=NextJS
Authorization: Bearer {{token}}

###
@jobPostId3 = {{postThree.response.body.$.content[0].id}}
###


### Apply 
# @name apply
POST {{baseURL}}/api/recruitment/job-posting/{{jobPostId1}}/apply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "fox.mulder@test.io",
    "phoneNumber": "",
    "source": "NoFluffJobs"
}

### Apply 
# @name apply
POST {{baseURL}}/api/recruitment/job-posting/{{jobPostId2}}/apply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "fox.mulder@test.io",
    "phoneNumber": "",
    "source": "NoFluffJobs"
}

### Apply 
# @name apply
POST {{baseURL}}/api/recruitment/job-posting/{{jobPostId3}}/apply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "fox.mulder@test.io",
    "phoneNumber": "",
    "source": "NoFluffJobs"
}


###
@companyId = {{apply.response.body.$.companyId}}
@candidateId = {{apply.response.body.$.candidateId}}
###

### Apply 
POST {{baseURL}}/api/recruitment/job-posting/{{jobPostId1}}/apply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "fox.mulder@test.io",
    "phoneNumber": "",
    "source": "RecruitmentAgency"
}

### Apply 
POST {{baseURL}}/api/recruitment/job-posting/{{jobPostId1}}/apply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "jerry.seinfeld@test.io",
    "phoneNumber": "",
    "source": "RecruitmentAgency"
}


###
GET {{baseURL}}/api/recruitment/candidates?companyId={{companyId}}
Authorization: Bearer {{token}}

###
GET {{baseURL}}/api/recruitment/candidates/{{candidateId}}
Authorization: Bearer {{token}}


###
# Get Tags
# @name getTagId1
GET {{baseURL}}/api/suggestion/tags?search=Azure Functions
Authorization: Bearer {{token}}

###
@tagId1 = {{getTagId1.response.body.$.[0].id}}
###

###
# Get Tags
# @name getTagId2
GET {{baseURL}}/api/suggestion/tags?search=React
Authorization: Bearer {{token}}

###
@tagId2 = {{getTagId2.response.body.$.[0].id}}
###


### Tag candidate

PUT {{baseURL}}/api/recruitment/candidates/{{candidateId}}/tag
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tagId": "{{tagId1}}"
}

### Tag candidate

PUT {{baseURL}}/api/recruitment/candidates/{{candidateId}}/tag
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tagId": "{{tagId2}}"
}

### Remove Tag candidate

DELETE  {{baseURL}}/api/recruitment/candidates/{{candidateId}}/tag/{{tagId2}}
Authorization: Bearer {{token}}


###
GET {{baseURL}}/api/recruitment/candidates?tag={{tagId2}}&tag={{tagId1}}
Authorization: Bearer {{token}}