@baseURL = http://localhost:5000

### Login Platform User
# @name login
POST {{baseURL}}/api/auth/login
Content-Type: application/json

{
    "email": "j.smith@hr-agency.com",
    "password": "test123",
    "slug": "hr-agency"
}

###
@token = {{login.response.body.$.token}}

###

###
# @name app1
GET {{baseURL}}/api/recruitment/job-applications?search=Joe
Authorization: Bearer {{token}}


###
# @name app1
GET {{baseURL}}/api/recruitment/job-applications?search=Monica
Authorization: Bearer {{token}}

###
# @name app1
GET {{baseURL}}/api/recruitment/job-applications?search=Rachel
Authorization: Bearer {{token}}

###
@appId1 = {{app1.response.body.$.content[0].id}}
@candidateId1 = {{app1.response.body.$.content[0].candidateId}}
@companyId1 = {{app1.response.body.$.content[0].companyId}}
###

###
GET {{baseURL}}/api/recruitment/candidates/{{candidateId1}}
Authorization: Bearer {{token}}

###
GET {{baseURL}}/api/recruitment/job-applications?pageSize=500&source=DirectSourcing
Authorization: Bearer {{token}}

###
GET {{baseURL}}/api/recruitment/job-applications?pageSize=20&companyId={{companyId1}}
Authorization: Bearer {{token}}


###
# Get Tags
# @name getTagId1
GET {{baseURL}}/api/suggestion/tags?search=Typescript
Authorization: Bearer {{token}}

###
@tagId1 = {{getTagId1.response.body.$.[0].id}}
###

###
# Get Tags
# @name getTagId2
GET {{baseURL}}/api/suggestion/tags?search=React
Authorization: Bearer {{token}}

###
@tagId2 = {{getTagId2.response.body.$.[0].id}}
###


### Tag application

PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/tag
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tagId": "{{tagId1}}"
}

### Tag application

PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/tag
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tagId": "{{tagId2}}"
}


### Remove tag application

DELETE {{baseURL}}/api/recruitment/job-applications/{{appId1}}/tag/{{tagId2}}
Authorization: Bearer {{token}}


### Get application

GET {{baseURL}}/api/recruitment/job-applications/{{appId1}}
Authorization: Bearer {{token}}
Content-Type: application/json


###
GET {{baseURL}}/api/recruitment/job-applications?tag={{tagId1}}
Authorization: Bearer {{token}}


###
GET {{baseURL}}/api/recruitment/job-applications?tag={{tagId1}}&tag={{tagId2}}
Authorization: Bearer {{token}}


###
# @name post1
GET {{baseURL}}/api/recruitment/job-posting?search=JAVA
Authorization: Bearer {{token}}

###
@postId1 = {{post1.response.body.$.content[0].id}}
###


### POST new application
# @name applyRandom
POST {{baseURL}}/api/recruitment/job-posting/{{postId1}}/apply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Email": "email{{$randomInt 9999 99999}}@fake.io",
    "Source": "Direct",
    "PhoneNumber": ""
}

###

@appId1 = {{applyRandom.response.body.$.jobApplicationId}}
@candidateId1 = {{applyRandom.response.body.$.candidateInfo.candidateId}}
@companyId1 = {{applyRandom.response.body.$.company.id}}

###

###
PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Screening",
    "note": "test 1"
}

###

PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Assessment",
    "note": "test 2"
}

###
PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Rejected",
    "note": "Does not know english language"
}

###
PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Interview",
    "interviewId": "{{$guid}}"   
}



###
PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Offer",
    "note": "Candidate was offered 1999 PLN"    
}


###
PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Hired",
    "note": "Candidate has all required skills. Offer was accepted"    
}

###
PUT {{baseURL}}/api/recruitment/job-applications/{{appId1}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Withdrawn",
    "note": "Candidate decided not proceed with employment"    
}

###
GET {{baseURL}}/api/recruitment/job-applications/{{appId1}}/notes
Authorization: Bearer {{token}}
