@baseURL = http://localhost:5000/api/organization
@baseLogin = http://localhost:5000

### Login Owner
# @name login
POST {{baseLogin}}/api/owner/login
Content-Type: application/json

{
    "email": "admin@hr-agency.com",
    "password": "pass123"
}

###
@token = {{login.response.body.$.token}}

### Create organization
# @name hrAgencyCreate
POST {{baseURL}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "HR Agency",
    "slug": "hr-agency"    
}

### Create organization without name
POST {{baseURL}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": " ",
    "slug": "hr-agency"
}

### Create random organization
# @name createOrganization
POST {{baseURL}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "HR Agency{{$randomInt 1000 9999}}",
    "slug": "hr-agency{{$randomInt 1000 9999}}"
}

###
@organizationId = {{createOrganization.response.body.$.organizationId}}

### Update organization slug
PUT {{baseURL}}/{{organizationId}}/slug
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "slug": "change-slug-{{$randomInt 1000 9999}}-{{$randomInt 1000 9999}}"
}


###
@hrAgencyId = {{createOrganization.response.body.$.organizationId}}
### Update organization slug
PUT {{baseURL}}/{{hrAgencyId}}/slug
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "slug": "hr-agency"
}

### Get 
GET {{baseURL}}
Authorization: Bearer {{token}}