@baseURL = http://localhost:5000

### Login Platform User
# @name login
POST {{baseURL}}/api/auth/login
Content-Type: application/json

{
    "email": "j.smith@hr-agency.com",
    "password": "test123",
    "slug": "hr-agency"
}

###
@token = {{login.response.body.$.token}}

###


### Get companies
# @name getCompanies
GET {{baseURL}}/api/companies?pageSize=1&page=1
Authorization: Bearer {{token}}
Content-Type: application/json


###

@companyId = {{getCompanies.response.body.content[0].id}}
###

###
# @name createOpportunity
POST {{baseURL}}/api/sales/opportunity
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "companyId": "{{companyId}}",
    "title": "Senior Dotnet Developre",
    "expectedValue": 200,
    "currency": "PLN"
}

###
@oportunityId = {{createOpportunity.response.body.opportunityId}}
###

###
PUT {{baseURL}}/api/sales/opportunity/{{oportunityId}}/stage
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "stage": "Lost",
    "lostReason": "Client went somewere else"
    
}

###
# @name changeStage
PUT {{baseURL}}/api/sales/opportunity/{{oportunityId}}/stage
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "stage": "Viewed"
    
}

###
PUT {{baseURL}}/api/sales/opportunity/{{oportunityId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    
    "title": "Senior .NET Developer With React",
    "expectedValue": 200,
    "currency": "EUR"
    
}


### Get user list
# @name getKate
GET {{baseURL}}/api/users?pageSize=100&search=kate
Authorization: Bearer {{token}}

###
@personId1 = {{getKate.response.body.$.content[0].id}}
###

### Get user list
# @name getJohn
GET {{baseURL}}/api/users?pageSize=100&search=John
Authorization: Bearer {{token}}

###
@personId2 = {{getJohn.response.body.$.content[0].id}}
###

###
# @name changeResponsible
PUT {{baseURL}}/api/sales/opportunity/{{oportunityId}}/responsible
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "responsibleId": "{{personId1}}"
    
}

###
# @name changeResponsible
PUT {{baseURL}}/api/sales/opportunity/{{oportunityId}}/responsible
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "responsibleId": "{{personId2}}"
    
}




###
# @name createActivity
POST {{baseURL}}/api/sales/activity
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "OpportunityId": "{{oportunityId}}",
    "Type": "Call",
    "Note": ""
}

###
# @name createActivity
POST {{baseURL}}/api/sales/activity
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "OpportunityId": "{{oportunityId}}",
    "Type": "Email",
    "Note": ""
}

###
# @name createActivity
POST {{baseURL}}/api/sales/activity
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "OpportunityId": "{{oportunityId}}",
    "Type": "Meeting",
    "Note": ""
}

