@baseURL = http://localhost:5000

### seed
GET {{baseURL}}/api/development/seed


### seed
GET {{baseURL}}/api/development/seed/random

### seed
GET {{baseURL}}/api/development/seed/show

### seed sales
GET {{baseURL}}/api/development/seed-sales?count=1000