/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CreateOrganizationRequest,
	GetApiOrganizationParams,
	ProblemDetails,
	UpdateSlug,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create organization
 */
export const postApiOrganization = (
	createOrganizationRequest: BodyType<CreateOrganizationRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{
			url: `/api/organization`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createOrganizationRequest,
			signal,
		},
		options,
	);
};

export const getPostApiOrganizationQueryKey = (
	createOrganizationRequest?: BodyType<CreateOrganizationRequest>,
) => {
	return ["POST", `/api/organization`, createOrganizationRequest] as const;
};

export const getPostApiOrganizationQueryOptions = <
	TData = Awaited<ReturnType<typeof postApiOrganization>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createOrganizationRequest: BodyType<CreateOrganizationRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiOrganization>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getPostApiOrganizationQueryKey(createOrganizationRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiOrganization>>> = ({ signal }) =>
		postApiOrganization(createOrganizationRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof postApiOrganization>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiOrganizationQueryResult = NonNullable<
	Awaited<ReturnType<typeof postApiOrganization>>
>;
export type PostApiOrganizationQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function usePostApiOrganization<
	TData = Awaited<ReturnType<typeof postApiOrganization>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createOrganizationRequest: BodyType<CreateOrganizationRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiOrganization>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiOrganization>>,
					TError,
					Awaited<ReturnType<typeof postApiOrganization>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiOrganization<
	TData = Awaited<ReturnType<typeof postApiOrganization>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createOrganizationRequest: BodyType<CreateOrganizationRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiOrganization>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiOrganization>>,
					TError,
					Awaited<ReturnType<typeof postApiOrganization>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiOrganization<
	TData = Awaited<ReturnType<typeof postApiOrganization>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createOrganizationRequest: BodyType<CreateOrganizationRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiOrganization>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create organization
 */

export function usePostApiOrganization<
	TData = Awaited<ReturnType<typeof postApiOrganization>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createOrganizationRequest: BodyType<CreateOrganizationRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiOrganization>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPostApiOrganizationQueryOptions(createOrganizationRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get organizations
 */
export const getApiOrganization = (
	params?: GetApiOrganizationParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>({ url: `/api/organization`, method: "GET", params, signal }, options);
};

export const getGetApiOrganizationMutationKey = () => ["getApiOrganization"] as const;

export const getGetApiOrganizationMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiOrganization>>,
		TError,
		GetApiOrganizationMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiOrganization>>,
	TError,
	GetApiOrganizationMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiOrganizationMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiOrganization>>,
		GetApiOrganizationMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiOrganization(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiOrganizationMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiOrganization>>
>;

export type GetApiOrganizationMutationError = ErrorType<unknown>;
export type GetApiOrganizationMutationVariables = { params?: GetApiOrganizationParams };

/**
 * @summary Get organizations
 */
export const useGetApiOrganization = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiOrganization>>,
			TError,
			GetApiOrganizationMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiOrganization>>,
	TError,
	GetApiOrganizationMutationVariables,
	TContext
> => {
	return useMutation(getGetApiOrganizationMutationOptions(options), queryClient);
};
/**
 * @summary Update organization slug
 */
export const putApiOrganizationOrganizationIdSlug = (
	organizationId: string,
	updateSlug: BodyType<UpdateSlug>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{
			url: `/api/organization/${organizationId}/slug`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateSlug,
			signal,
		},
		options,
	);
};

export const getPutApiOrganizationOrganizationIdSlugQueryKey = (
	organizationId: string,
	updateSlug?: BodyType<UpdateSlug>,
) => {
	return ["PUT", `/api/organization/${organizationId}/slug`, updateSlug] as const;
};

export const getPutApiOrganizationOrganizationIdSlugQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	organizationId: string,
	updateSlug: BodyType<UpdateSlug>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiOrganizationOrganizationIdSlugQueryKey(organizationId, updateSlug);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>
	> = ({ signal }) =>
		putApiOrganizationOrganizationIdSlug(organizationId, updateSlug, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: organizationId !== null && organizationId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiOrganizationOrganizationIdSlugQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>
>;
export type PutApiOrganizationOrganizationIdSlugQueryError = ErrorType<
	BadRequestDetails | ProblemDetails
>;

export function usePutApiOrganizationOrganizationIdSlug<
	TData = Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	organizationId: string,
	updateSlug: BodyType<UpdateSlug>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
					TError,
					Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiOrganizationOrganizationIdSlug<
	TData = Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	organizationId: string,
	updateSlug: BodyType<UpdateSlug>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
					TError,
					Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiOrganizationOrganizationIdSlug<
	TData = Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	organizationId: string,
	updateSlug: BodyType<UpdateSlug>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update organization slug
 */

export function usePutApiOrganizationOrganizationIdSlug<
	TData = Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	organizationId: string,
	updateSlug: BodyType<UpdateSlug>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiOrganizationOrganizationIdSlug>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiOrganizationOrganizationIdSlugQueryOptions(
		organizationId,
		updateSlug,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get organization by Slug
 */
export const getApiOrganizationSlug = (
	slug: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>({ url: `/api/organization/${slug}`, method: "GET", signal }, options);
};

export const getGetApiOrganizationSlugMutationKey = () => ["getApiOrganizationSlug"] as const;

export const getGetApiOrganizationSlugMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiOrganizationSlug>>,
		TError,
		GetApiOrganizationSlugMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiOrganizationSlug>>,
	TError,
	GetApiOrganizationSlugMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiOrganizationSlugMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiOrganizationSlug>>,
		GetApiOrganizationSlugMutationVariables
	> = (props) => {
		const { slug } = props ?? {};

		return getApiOrganizationSlug(slug, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiOrganizationSlugMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiOrganizationSlug>>
>;

export type GetApiOrganizationSlugMutationError = ErrorType<unknown>;
export type GetApiOrganizationSlugMutationVariables = { slug: string };

/**
 * @summary Get organization by Slug
 */
export const useGetApiOrganizationSlug = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiOrganizationSlug>>,
			TError,
			GetApiOrganizationSlugMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiOrganizationSlug>>,
	TError,
	GetApiOrganizationSlugMutationVariables,
	TContext
> => {
	return useMutation(getGetApiOrganizationSlugMutationOptions(options), queryClient);
};
