/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { UserSnapshot } from "./userSnapshot.ts";
import type { WorkerContractType } from "./workerContractType.ts";

export interface AgencyEmploymentStarted {
	organizationId: string;
	userId: string;
	user: UserSnapshot;
	contractType: WorkerContractType;
	startsOn: string;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
	 */
	weeklyHours: number | string | null;
	startedBy: UserSnapshot;
	startedAt: string;
}
