/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export interface ApproveTimeSheetRequest {
	/**
	 * Optional note to the person. Only their supervisor from the chart may approve.
	 * @nullable
	 */
	comment: string | null;
}
