/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { AssignmentDocument } from "./assignmentDocument.ts";
import type { AssignmentStatus } from "./assignmentStatus.ts";
import type { ComplianceItem } from "./complianceItem.ts";
import type { EngagementType } from "./engagementType.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface AssignmentProjection {
	id: string;
	organizationId: string;
	workerId: string;
	workerFullName: string;
	projectId: string;
	projectName: string;
	clientCompanyId: string;
	clientCompanyName: string;
	deliveringEntityId: string;
	deliveringEntityName: string;
	workCountry: string;
	engagementType: EngagementType;
	position: string;
	startsOn: string;
	/** @nullable */
	endsOn: string | null;
	status: AssignmentStatus;
	documents: AssignmentDocument[];
	compliance: ComplianceItem[];
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	documentCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	complianceRequiredCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	complianceOutstandingCount: number | string;
	/** @nullable */
	nextComplianceExpiryOn: string | null;
	createdById: string;
	createdBy: UserSnapshot;
	createdAt: string;
	/** @nullable */
	modifiedById: string | null;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
}
