/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { AssignmentPosition } from "./assignmentPosition.ts";
import type { EngagementType } from "./engagementType.ts";
import type { ProjectPlacementSnapshot } from "./projectPlacementSnapshot.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface AssignmentPlanned {
	assignmentId: string;
	organizationId: string;
	workerId: string;
	workerFullName: string;
	project: ProjectPlacementSnapshot;
	engagementType: EngagementType;
	position: AssignmentPosition;
	startsOn: string;
	/** @nullable */
	endsOn: string | null;
	createdBy: UserSnapshot;
	createdAt: string;
}
