/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { AssignmentDocumentCategory } from "./assignmentDocumentCategory.ts";
import type { IFormFile } from "./iFormFile.ts";

export type AttachAssignmentDocumentBody = {
	file?: IFormFile;
} & {
	category?: AssignmentDocumentCategory;
} & {
	documentDate?: string;
} & {
	validUntil?: string;
} & {
	note?: string;
} & Required<
		Pick<
			{
				file?: IFormFile;
			} & {
				category?: AssignmentDocumentCategory;
			} & {
				documentDate?: string;
			} & {
				validUntil?: string;
			} & {
				note?: string;
			},
			"file" | "category" | "documentDate"
		>
	>;
