/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type CandidateSource = (typeof CandidateSource)[keyof typeof CandidateSource];

export const CandidateSource = {
	CareerPage: "CareerPage",
	PracujPl: "PracujPl",
	Olx: "Olx",
	PracaPl: "PracaPl",
	RocketJobs: "RocketJobs",
	JustJoinIt: "JustJoinIt",
	NoFluffJobs: "NoFluffJobs",
	LinkedIn: "LinkedIn",
	Indeed: "Indeed",
	Referral: "Referral",
	DirectSourcing: "DirectSourcing",
	InternalDatabase: "InternalDatabase",
	RecruitmentAgency: "RecruitmentAgency",
	DirectApplication: "DirectApplication",
	Facebook: "Facebook",
	Other: "Other",
	Direct: "Direct",
} as const;
