/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ProjectStatus } from "./projectStatus.ts";

export interface ChangeProjectStatusRequest {
	/** Draft, Active, Suspended, Completed or Cancelled. Going Active needs a signed contract, a responsible contact and a complete client profile; Completed and Cancelled are final. */
	status: ProjectStatus;
	/**
	 * Optional note on why, up to 500 characters - worth giving for Suspended and Cancelled.
	 * @nullable
	 */
	reason: string | null;
}
