/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { OpportunityStage } from "./opportunityStage.ts";

export interface ChangeOpportunityStageRequest {
	/** The stage to move to: New, Viewed, Contacted, Qualified, Proposal, Won or Lost. */
	stage: OpportunityStage;
	/**
	 * Why the deal was lost - required when Stage is Lost, up to 500 characters, ignored otherwise.
	 * @nullable
	 */
	lostReason?: string | null;
}
