/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { AssignmentStatus } from "./assignmentStatus.ts";

export interface ChangeAssignmentStatusRequest {
	/** Planned, Active, Completed, Interrupted or DidNotStart. Active needs the person through the pipeline; Completed and Interrupted end a posting that ran, DidNotStart one that never did. */
	status: AssignmentStatus;
	/**
	 * The day it actually ended, for Completed or Interrupted; omit to keep the planned end. Ignored for other statuses.
	 * @nullable
	 */
	endsOn?: string | null;
	/**
	 * Optional note on the change - worth giving for Interrupted and DidNotStart.
	 * @nullable
	 */
	reason?: string | null;
}
