/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ContactPerson } from "./contactPerson";
import type { Industry } from "./industry";
import type { UserSnapshot } from "./userSnapshot";

export interface CompanyCreated {
	companyId: string;
	organizationId: string;
	name: string;
	countryCode: string;
	taxId: string;
	registrationNumber: string;
	industry: Industry;
	website: string;
	createdBy: UserSnapshot;
	createdAt: string;
	contact?: null | ContactPerson;
	/** @nullable */
	contactPersonId?: string | null;
}
