/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ContactPerson } from "./contactPerson.ts";
import type { PostalAddress } from "./postalAddress.ts";

export interface CompanyProfile {
	/** @nullable */
	legalName: string | null;
	registeredAddress: null | PostalAddress;
	/** @nullable */
	vatNumber: string | null;
	/** @nullable */
	iban: string | null;
	/** @nullable */
	bic: string | null;
	legalRepresentative: null | ContactPerson;
	isComplete?: boolean;
}
