/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type ComplianceRequirement =
	(typeof ComplianceRequirement)[keyof typeof ComplianceRequirement];

export const ComplianceRequirement = {
	A1Certificates: "A1Certificates",
	UserConditionsReceived: "UserConditionsReceived",
	BeLimosaDeclaration: "BeLimosaDeclaration",
	BeLiaisonPerson: "BeLiaisonPerson",
	BeJointCommittee: "BeJointCommittee",
	BeUserJointCommittee: "BeUserJointCommittee",
	BeTemporaryAgencyRecognition: "BeTemporaryAgencyRecognition",
	BeSocialDocumentsExemption: "BeSocialDocumentsExemption",
	BeMotivatedNotification: "BeMotivatedNotification",
	DeAentgNotification: "DeAentgNotification",
	DeAuegPermit: "DeAuegPermit",
	DeAuegNotification: "DeAuegNotification",
	DeAuthorisedRecipient: "DeAuthorisedRecipient",
	DeDocumentRetention: "DeDocumentRetention",
	DeBranchDetermination: "DeBranchDetermination",
	DeUeberlassungAgreement: "DeUeberlassungAgreement",
	DeConstructionSectorRestriction: "DeConstructionSectorRestriction",
	DeLongTermPostingNotification: "DeLongTermPostingNotification",
	DeServiceContractDelimitation: "DeServiceContractDelimitation",
	BeProhibitedPlacement: "BeProhibitedPlacement",
	LocalEmploymentContract: "LocalEmploymentContract",
	DeSocialSecurityRegistration: "DeSocialSecurityRegistration",
	BeDimonaDeclaration: "BeDimonaDeclaration",
} as const;
