/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { CompanyStatus } from "./companyStatus.ts";
import type { ContactPerson } from "./contactPerson.ts";
import type { Industry } from "./industry.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface CompanyProjection {
	id: string;
	organizationId: string;
	name: string;
	countryCode: string;
	taxId: string;
	registrationNumber: string;
	status: CompanyStatus;
	website: string;
	industry: Industry;
	createdId: string;
	createdBy: UserSnapshot;
	createdAt: string;
	/** @nullable */
	modifiedById: string | null;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	jobsPostCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	activeJobsPostCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	applicantsCount: number | string;
	contact: null | ContactPerson;
	/** @nullable */
	contactPersonId: string | null;
}
