/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { CurrencyCode } from "./currencyCode";

export interface CreateOpportunityRequest {
	companyId: string;
	title: string;
	description: string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
	expectedValue: number | string;
	isHotLead: boolean;
	currency: CurrencyCode;
	/** @nullable */
	expectedCloseDate: string | null;
	/** @nullable */
	responsibleId: string | null;
}
