/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { TaskPriority } from "./taskPriority.ts";

export interface CreateTaskRequest {
	/** The client company the task is for. Required. */
	companyId: string;
	/**
	 * One of that company's opportunities, when the task belongs to a deal.
	 * @nullable
	 */
	opportunityId: string | null;
	/** What has to be done, up to 200 characters. */
	title: string;
	/**
	 * Optional details, up to 2000 characters.
	 * @nullable
	 */
	description: string | null;
	/** When it has to be done by. */
	dueAt: string;
	/** Low, Medium or High. */
	priority: TaskPriority;
	/**
	 * Whose task it is; the caller's own when left out.
	 * @nullable
	 */
	assigneeId: string | null;
}
