/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ContactPerson } from "./contactPerson.ts";
import type { Industry } from "./industry.ts";

export interface CreateCompanyRequest {
	name: string;
	countryCode: string;
	taxId: string;
	registrationNumber: string;
	website: string;
	industry: Industry;
	contact?: null | ContactPerson;
}
