/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { EngagementType } from "./engagementType.ts";

export interface CreateProjectRequest {
	companyId: string;
	legalEntityId: string;
	name: string;
	description: string;
	engagementType: EngagementType;
	street: string;
	buildingNumber: string;
	/** @nullable */
	unitNumber: string | null;
	postalCode: string;
	city: string;
	countryCode: string;
	startsOn: string;
	/** @nullable */
	endsOn: string | null;
	/** @nullable */
	teamId: string | null;
}
