/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type DocumentCategory = (typeof DocumentCategory)[keyof typeof DocumentCategory];

export const DocumentCategory = {
	Contract: "Contract",
	Annex: "Annex",
	Invoice: "Invoice",
	ClientDocument: "ClientDocument",
	Compliance: "Compliance",
	Insurance: "Insurance",
	Other: "Other",
} as const;
