/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type FieldType = (typeof FieldType)[keyof typeof FieldType];

export const FieldType = {
	Text: "Text",
	TextArea: "TextArea",
	Number: "Number",
	Date: "Date",
	Boolean: "Boolean",
	SingleChoice: "SingleChoice",
	MultiChoice: "MultiChoice",
	Email: "Email",
	Phone: "Phone",
	Country: "Country",
} as const;
