/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { FormKind } from "./formKind.ts";
import type { FormPage } from "./formPage.ts";
import type { FormStatus } from "./formStatus.ts";
import type { FormVersionSummary } from "./formVersionSummary.ts";
import type { ResponseCardinality } from "./responseCardinality.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface FormDefinitionView {
	id: string;
	code: string;
	name: string;
	/** @nullable */
	description: string | null;
	kind: FormKind;
	cardinality: ResponseCardinality;
	subjectKind: string;
	status: FormStatus;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	publishedVersion: number | string;
	hasUnpublishedChanges: boolean;
	pages: FormPage[];
	versions: FormVersionSummary[];
	createdBy: UserSnapshot;
	createdAt: string;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
}
