/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { FormResponseProjectionAnswers } from "./formResponseProjectionAnswers.ts";
import type { FormResponseStatus } from "./formResponseStatus.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface FormResponseProjection {
	id: string;
	organizationId: string;
	formId: string;
	formCode: string;
	formName: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	formVersion: number | string;
	subjectKind: string;
	subjectId: string;
	status: FormResponseStatus;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	revision: number | string;
	answers: FormResponseProjectionAnswers;
	startedBy: UserSnapshot;
	startedAt: string;
	submittedBy: null | UserSnapshot;
	/** @nullable */
	submittedAt: string | null;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
}
