/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { FormPage } from "./formPage.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface FormPublished {
	organizationId: string;
	formId: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	version: number | string;
	pages: FormPage[];
	publishedBy: UserSnapshot;
	publishedAt: string;
}
