/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { FormLayoutPreviewFieldErrors } from "./formLayoutPreviewFieldErrors.ts";
import type { FormPage } from "./formPage.ts";

export interface FormLayoutPreview {
	pages: FormPage[];
	errors: string[];
	fieldErrors: FormLayoutPreviewFieldErrors;
	canPublish: boolean;
}
