/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { InterviewStatus } from "./interviewStatus";

export type GetApiInterviewsParams = {
	jobApplicationId?: string;
	interviewerId?: string;
	candidateId?: string;
	createdByUserId?: string;
	status?: InterviewStatus;
	fromDate?: string;
	toDate?: string;
	timezone?: string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	page?: number | string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	pageSize?: number | string;
};
