/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ResponsibleDepartment } from "./responsibleDepartment.ts";
import type { WorkerStatus } from "./workerStatus.ts";

export type GetWorkersParams = {
	search?: string;
	status?: WorkerStatus[];
	department?: ResponsibleDepartment[];
	workCountry?: string[];
	excludeWorkCountry?: string[];
	citizenship?: string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	page?: number | string;
	/**
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	pageSize?: number | string;
};
