/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type Industry = (typeof Industry)[keyof typeof Industry];

export const Industry = {
	Technology: "Technology",
	Software: "Software",
	Finance: "Finance",
	Banking: "Banking",
	Insurance: "Insurance",
	Accounting: "Accounting",
	HumanResources: "HumanResources",
	Consulting: "Consulting",
	Legal: "Legal",
	Marketing: "Marketing",
	Advertising: "Advertising",
	Sales: "Sales",
	Retail: "Retail",
	ECommerce: "ECommerce",
	Manufacturing: "Manufacturing",
	Metalworking: "Metalworking",
	Welding: "Welding",
	Machining: "Machining",
	CNC: "CNC",
	IndustrialProduction: "IndustrialProduction",
	MechanicalEngineering: "MechanicalEngineering",
	ElectricalEngineering: "ElectricalEngineering",
	Electronics: "Electronics",
	Automation: "Automation",
	Robotics: "Robotics",
	Assembly: "Assembly",
	IndustrialMaintenance: "IndustrialMaintenance",
	Toolmaking: "Toolmaking",
	Foundry: "Foundry",
	SheetMetal: "SheetMetal",
	Plastics: "Plastics",
	Woodworking: "Woodworking",
	Furniture: "Furniture",
	Textile: "Textile",
	Garment: "Garment",
	Packaging: "Packaging",
	Printing: "Printing",
	Construction: "Construction",
	CivilEngineering: "CivilEngineering",
	Architecture: "Architecture",
	RealEstate: "RealEstate",
	Infrastructure: "Infrastructure",
	Logistics: "Logistics",
	Transportation: "Transportation",
	SupplyChain: "SupplyChain",
	Warehousing: "Warehousing",
	Automotive: "Automotive",
	Aerospace: "Aerospace",
	Maritime: "Maritime",
	Energy: "Energy",
	Utilities: "Utilities",
	OilAndGas: "OilAndGas",
	RenewableEnergy: "RenewableEnergy",
	Mining: "Mining",
	Chemicals: "Chemicals",
	Healthcare: "Healthcare",
	Pharmaceuticals: "Pharmaceuticals",
	Biotechnology: "Biotechnology",
	Education: "Education",
	Government: "Government",
	PublicSector: "PublicSector",
	Hospitality: "Hospitality",
	Tourism: "Tourism",
	FoodAndBeverage: "FoodAndBeverage",
	Agriculture: "Agriculture",
	Security: "Security",
	CustomerService: "CustomerService",
	Media: "Media",
	Entertainment: "Entertainment",
	Sports: "Sports",
	NonProfit: "NonProfit",
	Other: "Other",
} as const;
