/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { CandidateInfo } from "./candidateInfo";
import type { InterviewFormat } from "./interviewFormat";
import type { InterviewType } from "./interviewType";
import type { UserSnapshot } from "./userSnapshot";

export interface InterviewCreated {
	interviewId: string;
	organizationId: string;
	jobApplicationId: string;
	candidateId: string;
	companyId: string;
	scheduleAt: string;
	timezone: string;
	interviewer: UserSnapshot;
	format: InterviewFormat;
	interviewType: InterviewType;
	note: string;
	author: UserSnapshot;
	occurredAt: string;
	candidate: CandidateInfo;
}
