/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { UserSnapshot } from "./userSnapshot";

export interface InterviewRescheduled {
	interviewId: string;
	organizationId: string;
	scheduleAt: string;
	timezone: string;
	note: string;
	author: UserSnapshot;
	occurredAt: string;
}
