/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { CandidateInfo } from "./candidateInfo";
import type { CandidateSource } from "./candidateSource";
import type { CompanySnapshot } from "./companySnapshot";
import type { JobApplicationStatus } from "./jobApplicationStatus";
import type { Tag } from "./tag";
import type { UserSnapshot } from "./userSnapshot";

export interface JobApplicationProjection {
	id: string;
	orgId: string;
	jobPostTitle: string;
	applicantEmail: string;
	applicantPhone: string;
	applicantFullName: string;
	candidateId: string;
	candidateInfo: CandidateInfo;
	source: CandidateSource;
	status: JobApplicationStatus;
	/** @nullable */
	latestInterviewId: string | null;
	/** @nullable */
	modifiedById: string | null;
	modifiedBy: null | UserSnapshot;
	createdAt: string;
	updatedAt: string;
	tags: Tag[];
	tagsIds: string[];
	companyId: string;
	company: CompanySnapshot;
	applicantFirstName: string;
	applicantLastName: string;
}
