/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { BankAccountPurpose } from "./bankAccountPurpose.ts";
import type { CurrencyCode } from "./currencyCode.ts";

export interface LegalEntityBankAccount {
	purpose: BankAccountPurpose;
	currency: CurrencyCode;
	iban: string;
	/** @nullable */
	bic: string | null;
	/** @nullable */
	bankName: string | null;
}
