/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { CompanySnapshot } from "./companySnapshot.ts";
import type { CurrencyCode } from "./currencyCode.ts";
import type { OpportunityStage } from "./opportunityStage.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface OpportunityProjection {
	id: string;
	organizationId: string;
	companyId: string;
	company: CompanySnapshot;
	title: string;
	description: string;
	stage: OpportunityStage;
	isHotLead: boolean;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
	expectedValue: number | string;
	currencyCode: CurrencyCode;
	/** @nullable */
	expectedCloseDate: string | null;
	lostReason: string;
	responsibleId: string;
	responsible: UserSnapshot;
	createdAt: string;
	createdBy: UserSnapshot;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
}
