/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { OrganizationInfoData } from "./organizationInfoData.ts";

export interface OrganizationProjection {
	id: string;
	name: string;
	slug: string;
	createdAt: string;
	/** @nullable */
	modifiedAt: string | null;
	emailDomains: string[];
	info: OrganizationInfoData;
}
