/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { EngagementType } from "./engagementType.ts";
import type { RateBasis } from "./rateBasis.ts";
import type { RateUnit } from "./rateUnit.ts";
import type { WorkerContractType } from "./workerContractType.ts";

export interface PositionRequest {
	name: string;
	/** @nullable */
	contractName: string | null;
	/** @nullable */
	workDescription: string | null;
	/** @nullable */
	duties: string[] | null;
	/** @nullable */
	requiredQualifications: string[] | null;
	contractType: WorkerContractType;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
	 */
	rateAmount: number | string | null;
	/** @nullable */
	rateCurrency: string | null;
	rateUnit: RateUnit;
	rateBasis: RateBasis;
	/** @nullable */
	street: string | null;
	/** @nullable */
	buildingNumber: string | null;
	/** @nullable */
	unitNumber: string | null;
	/** @nullable */
	postalCode: string | null;
	/** @nullable */
	city: string | null;
	/** @nullable */
	countryCode: string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
	 */
	weeklyHours: number | string | null;
	/** @nullable */
	workStartsAt: string | null;
	/** @nullable */
	workSchedule: string | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	payoutDay: number | string | null;
	/** @nullable */
	probationPeriod: string | null;
	/** @nullable */
	noticePeriod: string | null;
	/** @nullable */
	allowances: string[] | null;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	plannedHeadcount: number | string | null;
	defaultEngagementType: null | EngagementType;
}
