/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { PostingChannelType } from "./postingChannelType.ts";

export interface PostToChannelRequest {
	/** Where the post went: CareerPage, PracujPl, Olx, PracaPl, Rocketjobs, JustJoinIt, NoFluffJobs, Linkedin, Indeed or Other. It records the publication, it does not publish anything. A post not yet published becomes Published; a closed one is refused. */
	channel: PostingChannelType;
}
