/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ContactPerson } from "./contactPerson.ts";
import type { ContactRole } from "./contactRole.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface ProjectContactAssigned {
	projectId: string;
	organizationId: string;
	role: ContactRole;
	person: ContactPerson;
	/** @nullable */
	companyContactId: string | null;
	previousPerson: null | ContactPerson;
	modifiedBy: UserSnapshot;
	modifiedAt: string;
}
