/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ComplianceItem } from "./complianceItem.ts";
import type { ContactPerson } from "./contactPerson.ts";
import type { DeliveringEntitySnapshot } from "./deliveringEntitySnapshot.ts";
import type { EngagementType } from "./engagementType.ts";
import type { PostalAddress } from "./postalAddress.ts";
import type { ProjectContact } from "./projectContact.ts";
import type { ProjectContract } from "./projectContract.ts";
import type { ProjectDocument } from "./projectDocument.ts";
import type { ProjectEmailRecipient } from "./projectEmailRecipient.ts";
import type { ProjectStatus } from "./projectStatus.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface ProjectProjection {
	id: string;
	organizationId: string;
	companyId: string;
	companyName: string;
	companyTaxId: string;
	deliveringEntity: DeliveringEntitySnapshot;
	name: string;
	description: string;
	status: ProjectStatus;
	engagementType: EngagementType;
	workCountry: string;
	workplaceAddress: PostalAddress;
	startsOn: string;
	/** @nullable */
	endsOn: string | null;
	/** @nullable */
	teamId: string | null;
	/** @nullable */
	teamName: string | null;
	contacts: ProjectContact[];
	responsibleContact: null | ContactPerson;
	emailRecipients: ProjectEmailRecipient[];
	contract: null | ProjectContract;
	documents: ProjectDocument[];
	compliance: ComplianceItem[];
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	documentCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	complianceRequiredCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	complianceOutstandingCount: number | string;
	/** @nullable */
	nextComplianceExpiryOn: string | null;
	createdById: string;
	createdBy: UserSnapshot;
	createdAt: string;
	/** @nullable */
	modifiedById: string | null;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
}
