/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { DocumentCategory } from "./documentCategory.ts";

export interface ProjectDocument {
	documentId: string;
	category: DocumentCategory;
	fileId: string;
	fileName: string;
	contentType: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	size: number | string;
	documentDate: string;
	/** @nullable */
	validUntil: string | null;
	/** @nullable */
	note: string | null;
}
