/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { WorkAuthorisationKind } from "./workAuthorisationKind.ts";

export interface RecordWorkAuthorisationRequest {
	/** WorkPermit, ResidencePermit, Visa, WorkStatement or Other. */
	kind: WorkAuthorisationKind;
	/** Country the permission is for, ISO 3166-1 alpha-2. */
	country: string;
	/** The permission's number, as issued. */
	number: string;
	/** First day it is valid. */
	validFrom: string;
	/** Last day it is valid. */
	validUntil: string;
	/**
	 * Omit to add a permission; give the id of one on the file to replace it.
	 * @nullable
	 */
	authorisationId?: string | null;
	/**
	 * Optional document on the person's file that proves it.
	 * @nullable
	 */
	documentId?: string | null;
	/**
	 * Optional note.
	 * @nullable
	 */
	note?: string | null;
}
