/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { ContractStatus } from "./contractStatus.ts";

export interface RecordProjectContractRequest {
	/** The contract's number as written on it. */
	contractNumber: string;
	/** Draft, Signed, Terminated or Expired. A project goes live only with a Signed one. */
	status: ContractStatus;
	/**
	 * Signature date - required for a Signed contract, and not after ValidFrom.
	 * @nullable
	 */
	signedOn: string | null;
	/** First day the contract applies. */
	validFrom: string;
	/**
	 * Last day it applies. Optional; not before ValidFrom.
	 * @nullable
	 */
	validTo: string | null;
}
