/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export interface RefreshTokenRequest {
	/** The refresh token received at sign-in or at the last refresh. It is spent by this call and replaced by a new one; presenting a spent token again revokes the whole session. */
	refreshToken: string;
}
