/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { CurrencyCode } from "./currencyCode";
import type { OpportunityStage } from "./opportunityStage";
import type { UserSnapshot } from "./userSnapshot";

export interface SalesPipelineResponsibleQueryResult {
	stage: OpportunityStage;
	currencyCode: CurrencyCode;
	responsibleId: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	count: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
	totalExpectedValue: number | string;
	responsible: null | UserSnapshot;
}
