/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export interface SaveWorkDayRequest {
	/** The day, in a month that has already begun. The sheet is found from it; saving the same day again replaces it. */
	date: string;
	/** When work started, e.g. "08:00". A shift may run past midnight and still belongs to this day. */
	startsAt: string;
	/**
	 * Whole hours worked, 0 to 24.
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	hours: number | string;
	/**
	 * Minutes on top of Hours, 0 to 55 in steps of five. The day as a whole cannot be empty or longer than 24 hours.
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	minutes: number | string;
	/**
	 * Optional short note about the day.
	 * @nullable
	 */
	note: string | null;
}
