/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type TagCategory = (typeof TagCategory)[keyof typeof TagCategory];

export const TagCategory = {
	Language: "Language",
	SkillIt: "SkillIt",
	ProductionSkill: "ProductionSkill",
	DrivingLicense: "DrivingLicense",
} as const;
