/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { TimeSheetStatus } from "./timeSheetStatus.ts";
import type { UserSnapshot } from "./userSnapshot.ts";

export interface TeamTimeSheetRow {
	userId: string;
	user: UserSnapshot;
	status: null | TimeSheetStatus;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalMinutes: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	filledDays: number | string;
	/** @nullable */
	lastEntryOn: string | null;
	/** @nullable */
	submittedAt: string | null;
	hasStarted?: boolean;
}
