/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { TimeSheetComment } from "./timeSheetComment.ts";
import type { TimeSheetStatus } from "./timeSheetStatus.ts";
import type { UserSnapshot } from "./userSnapshot.ts";
import type { WorkDay } from "./workDay.ts";

export interface TimeSheetProjection {
	id: string;
	organizationId: string;
	userId: string;
	user: UserSnapshot;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	year: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	month: number | string;
	status: TimeSheetStatus;
	days: WorkDay[];
	comments: TimeSheetComment[];
	createdAt: string;
	modifiedBy: null | UserSnapshot;
	/** @nullable */
	modifiedAt: string | null;
	/** @nullable */
	submittedAt: string | null;
	approvedBy: null | UserSnapshot;
	/** @nullable */
	approvedAt: string | null;
	settledBy: null | UserSnapshot;
	/** @nullable */
	settledAt: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	totalMinutes?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	filledDays?: number | string;
	/** @nullable */
	lastEntryOn?: string | null;
}
