/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { DocumentCategory } from "./documentCategory.ts";

export interface UpdateProjectDocumentRequest {
	/** Contract, Annex, Invoice, ClientDocument, Compliance, Insurance or Other. */
	category: DocumentCategory;
	/** The date on the document. */
	documentDate: string;
	/**
	 * Last day the document is valid, when it expires.
	 * @nullable
	 */
	validUntil: string | null;
	/**
	 * Optional note.
	 * @nullable
	 */
	note: string | null;
}
