/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export interface UpdateUserRequest {
	/** Sign-in e-mail address. Unique within the agency. */
	email: string;
	/** First name. */
	firstName: string;
	/** Last name. */
	lastName: string;
	/**
	 * Optional job title. Omitted or null clears it.
	 * @nullable
	 */
	jobTitle?: string | null;
	/**
	 * Optional phone number. Omitted or null clears it.
	 * @nullable
	 */
	phone?: string | null;
}
