/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export interface UpdateAssignmentRequest {
	/** The role in the same project. Changing it moves the person's seat from one role to the other; the project itself never changes - moving somebody ends one assignment and plans another. */
	positionId: string;
	/** First day of the posting. */
	startsOn: string;
	/**
	 * Last day of the posting, or null for open-ended.
	 * @nullable
	 */
	endsOn?: string | null;
}
