/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { IdentityDocumentKind } from "./identityDocumentKind.ts";

export interface WorkerRequest {
	firstName: string;
	lastName: string;
	dateOfBirth: string;
	citizenship: string;
	identityDocumentKind: IdentityDocumentKind;
	identityDocumentNumber: string;
	identityDocumentIssuingCountry: string;
	/** @nullable */
	identityDocumentValidUntil?: string | null;
	/** @nullable */
	email?: string | null;
	/** @nullable */
	phoneNumber?: string | null;
	/** @nullable */
	street?: string | null;
	/** @nullable */
	buildingNumber?: string | null;
	/** @nullable */
	unitNumber?: string | null;
	/** @nullable */
	postalCode?: string | null;
	/** @nullable */
	city?: string | null;
	/** @nullable */
	addressCountryCode?: string | null;
	/** @nullable */
	note?: string | null;
	/** @nullable */
	sourceCandidateId?: string | null;
	/** @nullable */
	sourceApplicationId?: string | null;
}
