/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { IdentityDocumentKind } from "./identityDocumentKind.ts";
import type { PostalAddress } from "./postalAddress.ts";
import type { ResponsibleDepartment } from "./responsibleDepartment.ts";
import type { UserSnapshot } from "./userSnapshot.ts";
import type { WorkAuthorisation } from "./workAuthorisation.ts";
import type { WorkerAssignmentSummary } from "./workerAssignmentSummary.ts";
import type { WorkerDocument } from "./workerDocument.ts";
import type { WorkerStatus } from "./workerStatus.ts";

export interface WorkerProjection {
	id?: string;
	organizationId?: string;
	firstName?: string;
	lastName?: string;
	fullName?: string;
	dateOfBirth?: string;
	citizenship?: string;
	requiresLegalisation?: boolean;
	identityDocumentKind?: IdentityDocumentKind;
	identityDocumentNumber?: string;
	identityDocumentIssuingCountry?: string;
	/** @nullable */
	identityDocumentValidUntil?: string | null;
	/** @nullable */
	email?: string | null;
	phoneNumber?: string;
	phoneDigits?: string;
	address?: null | PostalAddress;
	note?: string;
	status?: WorkerStatus;
	department?: ResponsibleDepartment;
	/** @nullable */
	sourceCandidateId?: string | null;
	documents?: WorkerDocument[];
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	documentCount?: number | string;
	authorisations?: WorkAuthorisation[];
	/** @nullable */
	nextAuthorisationExpiryOn?: string | null;
	assignments?: WorkerAssignmentSummary[];
	/** @nullable */
	currentWorkCountry?: string | null;
	/** @nullable */
	currentAssignmentId?: string | null;
	/** @nullable */
	currentProjectName?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	assignmentCount?: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	openAssignmentCount?: number | string;
	createdById?: string;
	createdBy?: UserSnapshot;
	createdAt?: string;
	/** @nullable */
	modifiedById?: string | null;
	modifiedBy?: null | UserSnapshot;
	/** @nullable */
	modifiedAt?: string | null;
}
