/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type WorkerDocumentCategory =
	(typeof WorkerDocumentCategory)[keyof typeof WorkerDocumentCategory];

export const WorkerDocumentCategory = {
	Identity: "Identity",
	EmploymentContract: "EmploymentContract",
	MedicalCertificate: "MedicalCertificate",
	HealthAndSafety: "HealthAndSafety",
	Qualification: "Qualification",
	Legalisation: "Legalisation",
	Other: "Other",
} as const;
