/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

export type WorkAuthorisationKind =
	(typeof WorkAuthorisationKind)[keyof typeof WorkAuthorisationKind];

export const WorkAuthorisationKind = {
	WorkPermit: "WorkPermit",
	ResidencePermit: "ResidencePermit",
	Visa: "Visa",
	WorkStatement: "WorkStatement",
	Other: "Other",
} as const;
