/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */
import type { UserSnapshot } from "./userSnapshot.ts";
import type { WorkerStatus } from "./workerStatus.ts";

export interface WorkerStatusChanged {
	workerId: string;
	organizationId: string;
	previousStatus: WorkerStatus;
	status: WorkerStatus;
	reason: string;
	changedBy: UserSnapshot;
	changedAt: string;
}
