/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CompanyContact,
	CompanyContactRequest,
	ProblemDetails,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create contact
 */
export const postApiCompanyContactsCompanyId = (
	companyId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CompanyContact>(
		{
			url: `/api/company-contacts/${companyId}`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: companyContactRequest,
			signal,
		},
		options,
	);
};

export const getPostApiCompanyContactsCompanyIdQueryKey = (
	companyId: string,
	companyContactRequest?: BodyType<CompanyContactRequest>,
) => {
	return ["POST", `/api/company-contacts/${companyId}`, companyContactRequest] as const;
};

export const getPostApiCompanyContactsCompanyIdQueryOptions = <
	TData = Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	companyId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPostApiCompanyContactsCompanyIdQueryKey(companyId, companyContactRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>> = ({
		signal,
	}) => postApiCompanyContactsCompanyId(companyId, companyContactRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: companyId !== null && companyId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiCompanyContactsCompanyIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>
>;
export type PostApiCompanyContactsCompanyIdQueryError = ErrorType<
	BadRequestDetails | ProblemDetails
>;

export function usePostApiCompanyContactsCompanyId<
	TData = Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	companyId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
					TError,
					Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiCompanyContactsCompanyId<
	TData = Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	companyId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
					TError,
					Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiCompanyContactsCompanyId<
	TData = Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	companyId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create contact
 */

export function usePostApiCompanyContactsCompanyId<
	TData = Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	companyId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiCompanyContactsCompanyId>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPostApiCompanyContactsCompanyIdQueryOptions(
		companyId,
		companyContactRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get contacts
 */
export const getApiCompanyContactsCompanyId = (
	companyId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CompanyContact[]>(
		{ url: `/api/company-contacts/${companyId}`, method: "GET", signal },
		options,
	);
};

export const getGetApiCompanyContactsCompanyIdMutationKey = () =>
	["getApiCompanyContactsCompanyId"] as const;

export const getGetApiCompanyContactsCompanyIdMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiCompanyContactsCompanyId>>,
		TError,
		GetApiCompanyContactsCompanyIdMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiCompanyContactsCompanyId>>,
	TError,
	GetApiCompanyContactsCompanyIdMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiCompanyContactsCompanyIdMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiCompanyContactsCompanyId>>,
		GetApiCompanyContactsCompanyIdMutationVariables
	> = (props) => {
		const { companyId } = props ?? {};

		return getApiCompanyContactsCompanyId(companyId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiCompanyContactsCompanyIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiCompanyContactsCompanyId>>
>;

export type GetApiCompanyContactsCompanyIdMutationError = ErrorType<
	BadRequestDetails | ProblemDetails
>;
export type GetApiCompanyContactsCompanyIdMutationVariables = { companyId: string };

/**
 * @summary Get contacts
 */
export const useGetApiCompanyContactsCompanyId = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiCompanyContactsCompanyId>>,
			TError,
			GetApiCompanyContactsCompanyIdMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiCompanyContactsCompanyId>>,
	TError,
	GetApiCompanyContactsCompanyIdMutationVariables,
	TContext
> => {
	return useMutation(getGetApiCompanyContactsCompanyIdMutationOptions(options), queryClient);
};
/**
 * @summary Update contact
 */
export const putApiCompanyContactsContactId = (
	contactId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CompanyContact>(
		{
			url: `/api/company-contacts/${contactId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: companyContactRequest,
			signal,
		},
		options,
	);
};

export const getPutApiCompanyContactsContactIdQueryKey = (
	contactId: string,
	companyContactRequest?: BodyType<CompanyContactRequest>,
) => {
	return ["PUT", `/api/company-contacts/${contactId}`, companyContactRequest] as const;
};

export const getPutApiCompanyContactsContactIdQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	contactId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof putApiCompanyContactsContactId>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiCompanyContactsContactIdQueryKey(contactId, companyContactRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiCompanyContactsContactId>>> = ({
		signal,
	}) => putApiCompanyContactsContactId(contactId, companyContactRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: contactId !== null && contactId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiCompanyContactsContactIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiCompanyContactsContactId>>
>;
export type PutApiCompanyContactsContactIdQueryError = ErrorType<
	BadRequestDetails | ProblemDetails
>;

export function usePutApiCompanyContactsContactId<
	TData = Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	contactId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof putApiCompanyContactsContactId>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
					TError,
					Awaited<ReturnType<typeof putApiCompanyContactsContactId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiCompanyContactsContactId<
	TData = Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	contactId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof putApiCompanyContactsContactId>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
					TError,
					Awaited<ReturnType<typeof putApiCompanyContactsContactId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiCompanyContactsContactId<
	TData = Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	contactId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof putApiCompanyContactsContactId>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update contact
 */

export function usePutApiCompanyContactsContactId<
	TData = Awaited<ReturnType<typeof putApiCompanyContactsContactId>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	contactId: string,
	companyContactRequest: BodyType<CompanyContactRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof putApiCompanyContactsContactId>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiCompanyContactsContactIdQueryOptions(
		contactId,
		companyContactRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
