/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	ChangeOpportunityStageRequest,
	ChangeResponsiblePersonRequest,
	CreateOpportunityRequest,
	CreateSalesActivityRequest,
	GetApiSalesActivitiesParams,
	GetApiSalesOpportunityParams,
	GetApiSalesOpportunityTotalsParams,
	UpdateOpportunityRequest,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Log activity
 */
export const postApiSalesActivity = (
	createSalesActivityRequest: BodyType<CreateSalesActivityRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/sales/activity`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createSalesActivityRequest,
			signal,
		},
		options,
	);
};

export const getPostApiSalesActivityQueryKey = (
	createSalesActivityRequest?: BodyType<CreateSalesActivityRequest>,
) => {
	return ["POST", `/api/sales/activity`, createSalesActivityRequest] as const;
};

export const getPostApiSalesActivityQueryOptions = <
	TData = Awaited<ReturnType<typeof postApiSalesActivity>>,
	TError = ErrorType<unknown>,
>(
	createSalesActivityRequest: BodyType<CreateSalesActivityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesActivity>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getPostApiSalesActivityQueryKey(createSalesActivityRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiSalesActivity>>> = ({ signal }) =>
		postApiSalesActivity(createSalesActivityRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof postApiSalesActivity>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiSalesActivityQueryResult = NonNullable<
	Awaited<ReturnType<typeof postApiSalesActivity>>
>;
export type PostApiSalesActivityQueryError = ErrorType<unknown>;

export function usePostApiSalesActivity<
	TData = Awaited<ReturnType<typeof postApiSalesActivity>>,
	TError = ErrorType<unknown>,
>(
	createSalesActivityRequest: BodyType<CreateSalesActivityRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesActivity>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiSalesActivity>>,
					TError,
					Awaited<ReturnType<typeof postApiSalesActivity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiSalesActivity<
	TData = Awaited<ReturnType<typeof postApiSalesActivity>>,
	TError = ErrorType<unknown>,
>(
	createSalesActivityRequest: BodyType<CreateSalesActivityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesActivity>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiSalesActivity>>,
					TError,
					Awaited<ReturnType<typeof postApiSalesActivity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiSalesActivity<
	TData = Awaited<ReturnType<typeof postApiSalesActivity>>,
	TError = ErrorType<unknown>,
>(
	createSalesActivityRequest: BodyType<CreateSalesActivityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesActivity>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Log activity
 */

export function usePostApiSalesActivity<
	TData = Awaited<ReturnType<typeof postApiSalesActivity>>,
	TError = ErrorType<unknown>,
>(
	createSalesActivityRequest: BodyType<CreateSalesActivityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesActivity>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPostApiSalesActivityQueryOptions(createSalesActivityRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get activities
 */
export const getApiSalesActivities = (
	params?: GetApiSalesActivitiesParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/sales/activities`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiSalesActivitiesMutationKey = () => ["getApiSalesActivities"] as const;

export const getGetApiSalesActivitiesMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiSalesActivities>>,
		TError,
		GetApiSalesActivitiesMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiSalesActivities>>,
	TError,
	GetApiSalesActivitiesMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiSalesActivitiesMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiSalesActivities>>,
		GetApiSalesActivitiesMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiSalesActivities(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiSalesActivitiesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiSalesActivities>>
>;

export type GetApiSalesActivitiesMutationError = ErrorType<unknown>;
export type GetApiSalesActivitiesMutationVariables = { params?: GetApiSalesActivitiesParams };

/**
 * @summary Get activities
 */
export const useGetApiSalesActivities = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiSalesActivities>>,
			TError,
			GetApiSalesActivitiesMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiSalesActivities>>,
	TError,
	GetApiSalesActivitiesMutationVariables,
	TContext
> => {
	return useMutation(getGetApiSalesActivitiesMutationOptions(options), queryClient);
};
/**
 * @summary Create opportunity
 */
export const postApiSalesOpportunity = (
	createOpportunityRequest: BodyType<CreateOpportunityRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/sales/opportunity`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createOpportunityRequest,
			signal,
		},
		options,
	);
};

export const getPostApiSalesOpportunityQueryKey = (
	createOpportunityRequest?: BodyType<CreateOpportunityRequest>,
) => {
	return ["POST", `/api/sales/opportunity`, createOpportunityRequest] as const;
};

export const getPostApiSalesOpportunityQueryOptions = <
	TData = Awaited<ReturnType<typeof postApiSalesOpportunity>>,
	TError = ErrorType<unknown>,
>(
	createOpportunityRequest: BodyType<CreateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesOpportunity>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getPostApiSalesOpportunityQueryKey(createOpportunityRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiSalesOpportunity>>> = ({
		signal,
	}) => postApiSalesOpportunity(createOpportunityRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof postApiSalesOpportunity>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiSalesOpportunityQueryResult = NonNullable<
	Awaited<ReturnType<typeof postApiSalesOpportunity>>
>;
export type PostApiSalesOpportunityQueryError = ErrorType<unknown>;

export function usePostApiSalesOpportunity<
	TData = Awaited<ReturnType<typeof postApiSalesOpportunity>>,
	TError = ErrorType<unknown>,
>(
	createOpportunityRequest: BodyType<CreateOpportunityRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesOpportunity>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiSalesOpportunity>>,
					TError,
					Awaited<ReturnType<typeof postApiSalesOpportunity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiSalesOpportunity<
	TData = Awaited<ReturnType<typeof postApiSalesOpportunity>>,
	TError = ErrorType<unknown>,
>(
	createOpportunityRequest: BodyType<CreateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesOpportunity>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiSalesOpportunity>>,
					TError,
					Awaited<ReturnType<typeof postApiSalesOpportunity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiSalesOpportunity<
	TData = Awaited<ReturnType<typeof postApiSalesOpportunity>>,
	TError = ErrorType<unknown>,
>(
	createOpportunityRequest: BodyType<CreateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesOpportunity>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create opportunity
 */

export function usePostApiSalesOpportunity<
	TData = Awaited<ReturnType<typeof postApiSalesOpportunity>>,
	TError = ErrorType<unknown>,
>(
	createOpportunityRequest: BodyType<CreateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiSalesOpportunity>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPostApiSalesOpportunityQueryOptions(createOpportunityRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get opportunities
 */
export const getApiSalesOpportunity = (
	params?: GetApiSalesOpportunityParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/sales/opportunity`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiSalesOpportunityMutationKey = () => ["getApiSalesOpportunity"] as const;

export const getGetApiSalesOpportunityMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiSalesOpportunity>>,
		TError,
		GetApiSalesOpportunityMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiSalesOpportunity>>,
	TError,
	GetApiSalesOpportunityMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiSalesOpportunityMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiSalesOpportunity>>,
		GetApiSalesOpportunityMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiSalesOpportunity(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiSalesOpportunityMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiSalesOpportunity>>
>;

export type GetApiSalesOpportunityMutationError = ErrorType<unknown>;
export type GetApiSalesOpportunityMutationVariables = { params?: GetApiSalesOpportunityParams };

/**
 * @summary Get opportunities
 */
export const useGetApiSalesOpportunity = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiSalesOpportunity>>,
			TError,
			GetApiSalesOpportunityMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiSalesOpportunity>>,
	TError,
	GetApiSalesOpportunityMutationVariables,
	TContext
> => {
	return useMutation(getGetApiSalesOpportunityMutationOptions(options), queryClient);
};
/**
 * @summary Update opportunity
 */
export const putApiSalesOpportunityOpportunityId = (
	opportunityId: string,
	updateOpportunityRequest: BodyType<UpdateOpportunityRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/sales/opportunity/${opportunityId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateOpportunityRequest,
			signal,
		},
		options,
	);
};

export const getPutApiSalesOpportunityOpportunityIdQueryKey = (
	opportunityId: string,
	updateOpportunityRequest?: BodyType<UpdateOpportunityRequest>,
) => {
	return ["PUT", `/api/sales/opportunity/${opportunityId}`, updateOpportunityRequest] as const;
};

export const getPutApiSalesOpportunityOpportunityIdQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	updateOpportunityRequest: BodyType<UpdateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiSalesOpportunityOpportunityIdQueryKey(opportunityId, updateOpportunityRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>> = ({
		signal,
	}) =>
		putApiSalesOpportunityOpportunityId(
			opportunityId,
			updateOpportunityRequest,
			requestOptions,
			signal,
		);

	return {
		queryKey,
		queryFn,
		enabled: opportunityId !== null && opportunityId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiSalesOpportunityOpportunityIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>
>;
export type PutApiSalesOpportunityOpportunityIdQueryError = ErrorType<unknown>;

export function usePutApiSalesOpportunityOpportunityId<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	updateOpportunityRequest: BodyType<UpdateOpportunityRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
					TError,
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiSalesOpportunityOpportunityId<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	updateOpportunityRequest: BodyType<UpdateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
					TError,
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiSalesOpportunityOpportunityId<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	updateOpportunityRequest: BodyType<UpdateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update opportunity
 */

export function usePutApiSalesOpportunityOpportunityId<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	updateOpportunityRequest: BodyType<UpdateOpportunityRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiSalesOpportunityOpportunityIdQueryOptions(
		opportunityId,
		updateOpportunityRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get opportunity
 */
export const getApiSalesOpportunityOpportunityId = (
	opportunityId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/sales/opportunity/${opportunityId}`, method: "GET", signal },
		options,
	);
};

export const getGetApiSalesOpportunityOpportunityIdMutationKey = () =>
	["getApiSalesOpportunityOpportunityId"] as const;

export const getGetApiSalesOpportunityOpportunityIdMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiSalesOpportunityOpportunityId>>,
		TError,
		GetApiSalesOpportunityOpportunityIdMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiSalesOpportunityOpportunityId>>,
	TError,
	GetApiSalesOpportunityOpportunityIdMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiSalesOpportunityOpportunityIdMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiSalesOpportunityOpportunityId>>,
		GetApiSalesOpportunityOpportunityIdMutationVariables
	> = (props) => {
		const { opportunityId } = props ?? {};

		return getApiSalesOpportunityOpportunityId(opportunityId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiSalesOpportunityOpportunityIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiSalesOpportunityOpportunityId>>
>;

export type GetApiSalesOpportunityOpportunityIdMutationError = ErrorType<unknown>;
export type GetApiSalesOpportunityOpportunityIdMutationVariables = { opportunityId: string };

/**
 * @summary Get opportunity
 */
export const useGetApiSalesOpportunityOpportunityId = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiSalesOpportunityOpportunityId>>,
			TError,
			GetApiSalesOpportunityOpportunityIdMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiSalesOpportunityOpportunityId>>,
	TError,
	GetApiSalesOpportunityOpportunityIdMutationVariables,
	TContext
> => {
	return useMutation(getGetApiSalesOpportunityOpportunityIdMutationOptions(options), queryClient);
};
/**
 * @summary Change responsible person
 */
export const putApiSalesOpportunityOpportunityIdResponsible = (
	opportunityId: string,
	changeResponsiblePersonRequest: BodyType<ChangeResponsiblePersonRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/sales/opportunity/${opportunityId}/responsible`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changeResponsiblePersonRequest,
			signal,
		},
		options,
	);
};

export const getPutApiSalesOpportunityOpportunityIdResponsibleQueryKey = (
	opportunityId: string,
	changeResponsiblePersonRequest?: BodyType<ChangeResponsiblePersonRequest>,
) => {
	return [
		"PUT",
		`/api/sales/opportunity/${opportunityId}/responsible`,
		changeResponsiblePersonRequest,
	] as const;
};

export const getPutApiSalesOpportunityOpportunityIdResponsibleQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeResponsiblePersonRequest: BodyType<ChangeResponsiblePersonRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiSalesOpportunityOpportunityIdResponsibleQueryKey(
			opportunityId,
			changeResponsiblePersonRequest,
		);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>
	> = ({ signal }) =>
		putApiSalesOpportunityOpportunityIdResponsible(
			opportunityId,
			changeResponsiblePersonRequest,
			requestOptions,
			signal,
		);

	return {
		queryKey,
		queryFn,
		enabled: opportunityId !== null && opportunityId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiSalesOpportunityOpportunityIdResponsibleQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>
>;
export type PutApiSalesOpportunityOpportunityIdResponsibleQueryError = ErrorType<unknown>;

export function usePutApiSalesOpportunityOpportunityIdResponsible<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeResponsiblePersonRequest: BodyType<ChangeResponsiblePersonRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
					TError,
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiSalesOpportunityOpportunityIdResponsible<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeResponsiblePersonRequest: BodyType<ChangeResponsiblePersonRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
					TError,
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiSalesOpportunityOpportunityIdResponsible<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeResponsiblePersonRequest: BodyType<ChangeResponsiblePersonRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change responsible person
 */

export function usePutApiSalesOpportunityOpportunityIdResponsible<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeResponsiblePersonRequest: BodyType<ChangeResponsiblePersonRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdResponsible>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiSalesOpportunityOpportunityIdResponsibleQueryOptions(
		opportunityId,
		changeResponsiblePersonRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Change stage
 */
export const putApiSalesOpportunityOpportunityIdStage = (
	opportunityId: string,
	changeOpportunityStageRequest: BodyType<ChangeOpportunityStageRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/sales/opportunity/${opportunityId}/stage`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changeOpportunityStageRequest,
			signal,
		},
		options,
	);
};

export const getPutApiSalesOpportunityOpportunityIdStageQueryKey = (
	opportunityId: string,
	changeOpportunityStageRequest?: BodyType<ChangeOpportunityStageRequest>,
) => {
	return [
		"PUT",
		`/api/sales/opportunity/${opportunityId}/stage`,
		changeOpportunityStageRequest,
	] as const;
};

export const getPutApiSalesOpportunityOpportunityIdStageQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeOpportunityStageRequest: BodyType<ChangeOpportunityStageRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiSalesOpportunityOpportunityIdStageQueryKey(
			opportunityId,
			changeOpportunityStageRequest,
		);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>
	> = ({ signal }) =>
		putApiSalesOpportunityOpportunityIdStage(
			opportunityId,
			changeOpportunityStageRequest,
			requestOptions,
			signal,
		);

	return {
		queryKey,
		queryFn,
		enabled: opportunityId !== null && opportunityId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiSalesOpportunityOpportunityIdStageQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>
>;
export type PutApiSalesOpportunityOpportunityIdStageQueryError = ErrorType<unknown>;

export function usePutApiSalesOpportunityOpportunityIdStage<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeOpportunityStageRequest: BodyType<ChangeOpportunityStageRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
					TError,
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiSalesOpportunityOpportunityIdStage<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeOpportunityStageRequest: BodyType<ChangeOpportunityStageRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
					TError,
					Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiSalesOpportunityOpportunityIdStage<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeOpportunityStageRequest: BodyType<ChangeOpportunityStageRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change stage
 */

export function usePutApiSalesOpportunityOpportunityIdStage<
	TData = Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
	TError = ErrorType<unknown>,
>(
	opportunityId: string,
	changeOpportunityStageRequest: BodyType<ChangeOpportunityStageRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiSalesOpportunityOpportunityIdStage>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiSalesOpportunityOpportunityIdStageQueryOptions(
		opportunityId,
		changeOpportunityStageRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get pipeline totals
 */
export const getApiSalesOpportunityTotals = (
	params?: GetApiSalesOpportunityTotalsParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/sales/opportunity/totals`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiSalesOpportunityTotalsMutationKey = () =>
	["getApiSalesOpportunityTotals"] as const;

export const getGetApiSalesOpportunityTotalsMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiSalesOpportunityTotals>>,
		TError,
		GetApiSalesOpportunityTotalsMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiSalesOpportunityTotals>>,
	TError,
	GetApiSalesOpportunityTotalsMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiSalesOpportunityTotalsMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiSalesOpportunityTotals>>,
		GetApiSalesOpportunityTotalsMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiSalesOpportunityTotals(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiSalesOpportunityTotalsMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiSalesOpportunityTotals>>
>;

export type GetApiSalesOpportunityTotalsMutationError = ErrorType<unknown>;
export type GetApiSalesOpportunityTotalsMutationVariables = {
	params?: GetApiSalesOpportunityTotalsParams;
};

/**
 * @summary Get pipeline totals
 */
export const useGetApiSalesOpportunityTotals = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiSalesOpportunityTotals>>,
			TError,
			GetApiSalesOpportunityTotalsMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiSalesOpportunityTotals>>,
	TError,
	GetApiSalesOpportunityTotalsMutationVariables,
	TContext
> => {
	return useMutation(getGetApiSalesOpportunityTotalsMutationOptions(options), queryClient);
};
/**
 * @summary Get responsible totals
 */
export const getApiSalesOpportunityTotalsResponsible = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/sales/opportunity/totals-responsible`, method: "GET", signal },
		options,
	);
};

export const getGetApiSalesOpportunityTotalsResponsibleMutationKey = () =>
	["getApiSalesOpportunityTotalsResponsible"] as const;

export const getGetApiSalesOpportunityTotalsResponsibleMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiSalesOpportunityTotalsResponsible>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiSalesOpportunityTotalsResponsible>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = getGetApiSalesOpportunityTotalsResponsibleMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiSalesOpportunityTotalsResponsible>>,
		void
	> = () => {
		return getApiSalesOpportunityTotalsResponsible(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiSalesOpportunityTotalsResponsibleMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiSalesOpportunityTotalsResponsible>>
>;

export type GetApiSalesOpportunityTotalsResponsibleMutationError = ErrorType<unknown>;

/**
 * @summary Get responsible totals
 */
export const useGetApiSalesOpportunityTotalsResponsible = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiSalesOpportunityTotalsResponsible>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiSalesOpportunityTotalsResponsible>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getGetApiSalesOpportunityTotalsResponsibleMutationOptions(options),
		queryClient,
	);
};
