/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	AssignRecruiterRequest,
	BadRequestDetails,
	CreateJobDescriptionRequest,
	GetJobDescriptionStatusesHistoryParams,
	GetJobDescriptionsSliceParams,
	JdStatusChangeHistory,
	JobDescriptionCreated,
	JobDescriptionProjection,
	JobDescriptionRecruiterAssigned,
	JobDescriptionStatus,
	JobDescriptionUpdated,
	ProblemDetails,
	SliceResponseOfJobDescriptionProjection,
	UpdateJobDescriptionRequest,
	UpdateJobDescriptionStatusResult,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create job description
 */
export const createJobDescription = (
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<JobDescriptionCreated>(
		{
			url: `/api/job-description`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createJobDescriptionRequest,
			signal,
		},
		options,
	);
};

export const getCreateJobDescriptionQueryKey = (
	createJobDescriptionRequest?: BodyType<CreateJobDescriptionRequest>,
) => {
	return ["POST", `/api/job-description`, createJobDescriptionRequest] as const;
};

export const getCreateJobDescriptionQueryOptions = <
	TData = Awaited<ReturnType<typeof createJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof createJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getCreateJobDescriptionQueryKey(createJobDescriptionRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof createJobDescription>>> = ({ signal }) =>
		createJobDescription(createJobDescriptionRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof createJobDescription>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateJobDescriptionQueryResult = NonNullable<
	Awaited<ReturnType<typeof createJobDescription>>
>;
export type CreateJobDescriptionQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCreateJobDescription<
	TData = Awaited<ReturnType<typeof createJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof createJobDescription>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof createJobDescription>>,
					TError,
					Awaited<ReturnType<typeof createJobDescription>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateJobDescription<
	TData = Awaited<ReturnType<typeof createJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof createJobDescription>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof createJobDescription>>,
					TError,
					Awaited<ReturnType<typeof createJobDescription>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateJobDescription<
	TData = Awaited<ReturnType<typeof createJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof createJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create job description
 */

export function useCreateJobDescription<
	TData = Awaited<ReturnType<typeof createJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof createJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCreateJobDescriptionQueryOptions(createJobDescriptionRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get job descriptions
 */
export const getJobDescriptionsSlice = (
	params?: GetJobDescriptionsSliceParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfJobDescriptionProjection>(
		{ url: `/api/job-description`, method: "GET", params, signal },
		options,
	);
};

export const getGetJobDescriptionsSliceMutationKey = () => ["getJobDescriptionsSlice"] as const;

export const getGetJobDescriptionsSliceMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getJobDescriptionsSlice>>,
		TError,
		GetJobDescriptionsSliceMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getJobDescriptionsSlice>>,
	TError,
	GetJobDescriptionsSliceMutationVariables,
	TContext
> => {
	const mutationKey = getGetJobDescriptionsSliceMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getJobDescriptionsSlice>>,
		GetJobDescriptionsSliceMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getJobDescriptionsSlice(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetJobDescriptionsSliceMutationResult = NonNullable<
	Awaited<ReturnType<typeof getJobDescriptionsSlice>>
>;

export type GetJobDescriptionsSliceMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetJobDescriptionsSliceMutationVariables = { params?: GetJobDescriptionsSliceParams };

/**
 * @summary Get job descriptions
 */
export const useGetJobDescriptionsSlice = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getJobDescriptionsSlice>>,
			TError,
			GetJobDescriptionsSliceMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getJobDescriptionsSlice>>,
	TError,
	GetJobDescriptionsSliceMutationVariables,
	TContext
> => {
	return useMutation(getGetJobDescriptionsSliceMutationOptions(options), queryClient);
};
/**
 * @summary Update job description
 */
export const updateJobDescription = (
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<JobDescriptionUpdated>(
		{
			url: `/api/job-description/${jobDescriptionId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateJobDescriptionRequest,
			signal,
		},
		options,
	);
};

export const getUpdateJobDescriptionQueryKey = (
	jobDescriptionId: string,
	updateJobDescriptionRequest?: BodyType<UpdateJobDescriptionRequest>,
) => {
	return ["PUT", `/api/job-description/${jobDescriptionId}`, updateJobDescriptionRequest] as const;
};

export const getUpdateJobDescriptionQueryOptions = <
	TData = Awaited<ReturnType<typeof updateJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getUpdateJobDescriptionQueryKey(jobDescriptionId, updateJobDescriptionRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateJobDescription>>> = ({ signal }) =>
		updateJobDescription(jobDescriptionId, updateJobDescriptionRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: jobDescriptionId !== null && jobDescriptionId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof updateJobDescription>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UpdateJobDescriptionQueryResult = NonNullable<
	Awaited<ReturnType<typeof updateJobDescription>>
>;
export type UpdateJobDescriptionQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateJobDescription<
	TData = Awaited<ReturnType<typeof updateJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescription>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateJobDescription>>,
					TError,
					Awaited<ReturnType<typeof updateJobDescription>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateJobDescription<
	TData = Awaited<ReturnType<typeof updateJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescription>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateJobDescription>>,
					TError,
					Awaited<ReturnType<typeof updateJobDescription>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateJobDescription<
	TData = Awaited<ReturnType<typeof updateJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update job description
 */

export function useUpdateJobDescription<
	TData = Awaited<ReturnType<typeof updateJobDescription>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateJobDescriptionQueryOptions(
		jobDescriptionId,
		updateJobDescriptionRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get job description
 */
export const getJobDescription = (
	jobDescriptionId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<JobDescriptionProjection>(
		{ url: `/api/job-description/${jobDescriptionId}`, method: "GET", signal },
		options,
	);
};

export const getGetJobDescriptionMutationKey = () => ["getJobDescription"] as const;

export const getGetJobDescriptionMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getJobDescription>>,
		TError,
		GetJobDescriptionMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getJobDescription>>,
	TError,
	GetJobDescriptionMutationVariables,
	TContext
> => {
	const mutationKey = getGetJobDescriptionMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getJobDescription>>,
		GetJobDescriptionMutationVariables
	> = (props) => {
		const { jobDescriptionId } = props ?? {};

		return getJobDescription(jobDescriptionId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetJobDescriptionMutationResult = NonNullable<
	Awaited<ReturnType<typeof getJobDescription>>
>;

export type GetJobDescriptionMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetJobDescriptionMutationVariables = { jobDescriptionId: string };

/**
 * @summary Get job description
 */
export const useGetJobDescription = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getJobDescription>>,
			TError,
			GetJobDescriptionMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getJobDescription>>,
	TError,
	GetJobDescriptionMutationVariables,
	TContext
> => {
	return useMutation(getGetJobDescriptionMutationOptions(options), queryClient);
};
/**
 * @summary Assign recruiter
 */
export const assignJobDescriptionRecruiter = (
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<JobDescriptionRecruiterAssigned>(
		{
			url: `/api/job-description/${jobDescriptionId}/assign-recruiter`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: assignRecruiterRequest,
			signal,
		},
		options,
	);
};

export const getAssignJobDescriptionRecruiterQueryKey = (
	jobDescriptionId: string,
	assignRecruiterRequest?: BodyType<AssignRecruiterRequest>,
) => {
	return [
		"PUT",
		`/api/job-description/${jobDescriptionId}/assign-recruiter`,
		assignRecruiterRequest,
	] as const;
};

export const getAssignJobDescriptionRecruiterQueryOptions = <
	TData = Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getAssignJobDescriptionRecruiterQueryKey(jobDescriptionId, assignRecruiterRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>> = ({
		signal,
	}) =>
		assignJobDescriptionRecruiter(jobDescriptionId, assignRecruiterRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: jobDescriptionId !== null && jobDescriptionId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type AssignJobDescriptionRecruiterQueryResult = NonNullable<
	Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>
>;
export type AssignJobDescriptionRecruiterQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useAssignJobDescriptionRecruiter<
	TData = Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
					TError,
					Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAssignJobDescriptionRecruiter<
	TData = Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
					TError,
					Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAssignJobDescriptionRecruiter<
	TData = Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Assign recruiter
 */

export function useAssignJobDescriptionRecruiter<
	TData = Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof assignJobDescriptionRecruiter>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getAssignJobDescriptionRecruiterQueryOptions(
		jobDescriptionId,
		assignRecruiterRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get statuses history
 */
export const getJobDescriptionStatusesHistory = (
	params?: GetJobDescriptionStatusesHistoryParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<JdStatusChangeHistory[]>(
		{ url: `/api/job-description/status`, method: "GET", params, signal },
		options,
	);
};

export const getGetJobDescriptionStatusesHistoryMutationKey = () =>
	["getJobDescriptionStatusesHistory"] as const;

export const getGetJobDescriptionStatusesHistoryMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getJobDescriptionStatusesHistory>>,
		TError,
		GetJobDescriptionStatusesHistoryMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getJobDescriptionStatusesHistory>>,
	TError,
	GetJobDescriptionStatusesHistoryMutationVariables,
	TContext
> => {
	const mutationKey = getGetJobDescriptionStatusesHistoryMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getJobDescriptionStatusesHistory>>,
		GetJobDescriptionStatusesHistoryMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getJobDescriptionStatusesHistory(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetJobDescriptionStatusesHistoryMutationResult = NonNullable<
	Awaited<ReturnType<typeof getJobDescriptionStatusesHistory>>
>;

export type GetJobDescriptionStatusesHistoryMutationError = ErrorType<
	BadRequestDetails | ProblemDetails
>;
export type GetJobDescriptionStatusesHistoryMutationVariables = {
	params?: GetJobDescriptionStatusesHistoryParams;
};

/**
 * @summary Get statuses history
 */
export const useGetJobDescriptionStatusesHistory = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getJobDescriptionStatusesHistory>>,
			TError,
			GetJobDescriptionStatusesHistoryMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getJobDescriptionStatusesHistory>>,
	TError,
	GetJobDescriptionStatusesHistoryMutationVariables,
	TContext
> => {
	return useMutation(getGetJobDescriptionStatusesHistoryMutationOptions(options), queryClient);
};
/**
 * @summary Update status
 */
export const updateJobDescriptionStatus = (
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UpdateJobDescriptionStatusResult>(
		{ url: `/api/job-description/${jobDescriptionId}/${status}`, method: "PUT", signal },
		options,
	);
};

export const getUpdateJobDescriptionStatusQueryKey = (
	jobDescriptionId: string,
	status: JobDescriptionStatus,
) => {
	return ["PUT", `/api/job-description/${jobDescriptionId}/${status}`] as const;
};

export const getUpdateJobDescriptionStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescriptionStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getUpdateJobDescriptionStatusQueryKey(jobDescriptionId, status);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateJobDescriptionStatus>>> = ({
		signal,
	}) => updateJobDescriptionStatus(jobDescriptionId, status, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled:
			jobDescriptionId !== null &&
			jobDescriptionId !== undefined &&
			status !== null &&
			status !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof updateJobDescriptionStatus>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UpdateJobDescriptionStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof updateJobDescriptionStatus>>
>;
export type UpdateJobDescriptionStatusQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateJobDescriptionStatus<
	TData = Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescriptionStatus>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
					TError,
					Awaited<ReturnType<typeof updateJobDescriptionStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateJobDescriptionStatus<
	TData = Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescriptionStatus>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
					TError,
					Awaited<ReturnType<typeof updateJobDescriptionStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateJobDescriptionStatus<
	TData = Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescriptionStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update status
 */

export function useUpdateJobDescriptionStatus<
	TData = Awaited<ReturnType<typeof updateJobDescriptionStatus>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof updateJobDescriptionStatus>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateJobDescriptionStatusQueryOptions(jobDescriptionId, status, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
