/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	AssignRecruiterRequest,
	CreateJobDescriptionRequest,
	GetApiJobDescriptionParams,
	GetApiJobDescriptionStatusParams,
	JobDescriptionStatus,
	UpdateJobDescriptionRequest,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create job description
 */
export const postApiJobDescription = (
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/job-description`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createJobDescriptionRequest,
			signal,
		},
		options,
	);
};

export const getPostApiJobDescriptionQueryKey = (
	createJobDescriptionRequest?: BodyType<CreateJobDescriptionRequest>,
) => {
	return ["POST", `/api/job-description`, createJobDescriptionRequest] as const;
};

export const getPostApiJobDescriptionQueryOptions = <
	TData = Awaited<ReturnType<typeof postApiJobDescription>>,
	TError = ErrorType<unknown>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getPostApiJobDescriptionQueryKey(createJobDescriptionRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiJobDescription>>> = ({ signal }) =>
		postApiJobDescription(createJobDescriptionRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof postApiJobDescription>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiJobDescriptionQueryResult = NonNullable<
	Awaited<ReturnType<typeof postApiJobDescription>>
>;
export type PostApiJobDescriptionQueryError = ErrorType<unknown>;

export function usePostApiJobDescription<
	TData = Awaited<ReturnType<typeof postApiJobDescription>>,
	TError = ErrorType<unknown>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiJobDescription>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiJobDescription>>,
					TError,
					Awaited<ReturnType<typeof postApiJobDescription>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiJobDescription<
	TData = Awaited<ReturnType<typeof postApiJobDescription>>,
	TError = ErrorType<unknown>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiJobDescription>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiJobDescription>>,
					TError,
					Awaited<ReturnType<typeof postApiJobDescription>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiJobDescription<
	TData = Awaited<ReturnType<typeof postApiJobDescription>>,
	TError = ErrorType<unknown>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create job description
 */

export function usePostApiJobDescription<
	TData = Awaited<ReturnType<typeof postApiJobDescription>>,
	TError = ErrorType<unknown>,
>(
	createJobDescriptionRequest: BodyType<CreateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiJobDescription>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPostApiJobDescriptionQueryOptions(createJobDescriptionRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get job descriptions
 */
export const getApiJobDescription = (
	params?: GetApiJobDescriptionParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/job-description`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiJobDescriptionMutationKey = () => ["getApiJobDescription"] as const;

export const getGetApiJobDescriptionMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiJobDescription>>,
		TError,
		GetApiJobDescriptionMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiJobDescription>>,
	TError,
	GetApiJobDescriptionMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiJobDescriptionMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiJobDescription>>,
		GetApiJobDescriptionMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiJobDescription(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiJobDescriptionMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiJobDescription>>
>;

export type GetApiJobDescriptionMutationError = ErrorType<unknown>;
export type GetApiJobDescriptionMutationVariables = { params?: GetApiJobDescriptionParams };

/**
 * @summary Get job descriptions
 */
export const useGetApiJobDescription = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiJobDescription>>,
			TError,
			GetApiJobDescriptionMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiJobDescription>>,
	TError,
	GetApiJobDescriptionMutationVariables,
	TContext
> => {
	return useMutation(getGetApiJobDescriptionMutationOptions(options), queryClient);
};
/**
 * @summary Update job description
 */
export const putApiJobDescriptionJobDescriptionId = (
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/job-description/${jobDescriptionId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateJobDescriptionRequest,
			signal,
		},
		options,
	);
};

export const getPutApiJobDescriptionJobDescriptionIdQueryKey = (
	jobDescriptionId: string,
	updateJobDescriptionRequest?: BodyType<UpdateJobDescriptionRequest>,
) => {
	return ["PUT", `/api/job-description/${jobDescriptionId}`, updateJobDescriptionRequest] as const;
};

export const getPutApiJobDescriptionJobDescriptionIdQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiJobDescriptionJobDescriptionIdQueryKey(jobDescriptionId, updateJobDescriptionRequest);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>
	> = ({ signal }) =>
		putApiJobDescriptionJobDescriptionId(
			jobDescriptionId,
			updateJobDescriptionRequest,
			requestOptions,
			signal,
		);

	return {
		queryKey,
		queryFn,
		enabled: jobDescriptionId !== null && jobDescriptionId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiJobDescriptionJobDescriptionIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>
>;
export type PutApiJobDescriptionJobDescriptionIdQueryError = ErrorType<unknown>;

export function usePutApiJobDescriptionJobDescriptionId<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
					TError,
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiJobDescriptionJobDescriptionId<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
					TError,
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiJobDescriptionJobDescriptionId<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update job description
 */

export function usePutApiJobDescriptionJobDescriptionId<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	updateJobDescriptionRequest: BodyType<UpdateJobDescriptionRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiJobDescriptionJobDescriptionIdQueryOptions(
		jobDescriptionId,
		updateJobDescriptionRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get job description
 */
export const getApiJobDescriptionJobDescriptionId = (
	jobDescriptionId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/job-description/${jobDescriptionId}`, method: "GET", signal },
		options,
	);
};

export const getGetApiJobDescriptionJobDescriptionIdMutationKey = () =>
	["getApiJobDescriptionJobDescriptionId"] as const;

export const getGetApiJobDescriptionJobDescriptionIdMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiJobDescriptionJobDescriptionId>>,
		TError,
		GetApiJobDescriptionJobDescriptionIdMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiJobDescriptionJobDescriptionId>>,
	TError,
	GetApiJobDescriptionJobDescriptionIdMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiJobDescriptionJobDescriptionIdMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiJobDescriptionJobDescriptionId>>,
		GetApiJobDescriptionJobDescriptionIdMutationVariables
	> = (props) => {
		const { jobDescriptionId } = props ?? {};

		return getApiJobDescriptionJobDescriptionId(jobDescriptionId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiJobDescriptionJobDescriptionIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiJobDescriptionJobDescriptionId>>
>;

export type GetApiJobDescriptionJobDescriptionIdMutationError = ErrorType<unknown>;
export type GetApiJobDescriptionJobDescriptionIdMutationVariables = { jobDescriptionId: string };

/**
 * @summary Get job description
 */
export const useGetApiJobDescriptionJobDescriptionId = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiJobDescriptionJobDescriptionId>>,
			TError,
			GetApiJobDescriptionJobDescriptionIdMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiJobDescriptionJobDescriptionId>>,
	TError,
	GetApiJobDescriptionJobDescriptionIdMutationVariables,
	TContext
> => {
	return useMutation(getGetApiJobDescriptionJobDescriptionIdMutationOptions(options), queryClient);
};
/**
 * @summary Assign recruiter
 */
export const putApiJobDescriptionJobDescriptionIdAssignRecruiter = (
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{
			url: `/api/job-description/${jobDescriptionId}/assign-recruiter`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: assignRecruiterRequest,
			signal,
		},
		options,
	);
};

export const getPutApiJobDescriptionJobDescriptionIdAssignRecruiterQueryKey = (
	jobDescriptionId: string,
	assignRecruiterRequest?: BodyType<AssignRecruiterRequest>,
) => {
	return [
		"PUT",
		`/api/job-description/${jobDescriptionId}/assign-recruiter`,
		assignRecruiterRequest,
	] as const;
};

export const getPutApiJobDescriptionJobDescriptionIdAssignRecruiterQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiJobDescriptionJobDescriptionIdAssignRecruiterQueryKey(
			jobDescriptionId,
			assignRecruiterRequest,
		);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>
	> = ({ signal }) =>
		putApiJobDescriptionJobDescriptionIdAssignRecruiter(
			jobDescriptionId,
			assignRecruiterRequest,
			requestOptions,
			signal,
		);

	return {
		queryKey,
		queryFn,
		enabled: jobDescriptionId !== null && jobDescriptionId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiJobDescriptionJobDescriptionIdAssignRecruiterQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>
>;
export type PutApiJobDescriptionJobDescriptionIdAssignRecruiterQueryError = ErrorType<unknown>;

export function usePutApiJobDescriptionJobDescriptionIdAssignRecruiter<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
					TError,
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiJobDescriptionJobDescriptionIdAssignRecruiter<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
					TError,
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiJobDescriptionJobDescriptionIdAssignRecruiter<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Assign recruiter
 */

export function usePutApiJobDescriptionJobDescriptionIdAssignRecruiter<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	assignRecruiterRequest: BodyType<AssignRecruiterRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdAssignRecruiter>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiJobDescriptionJobDescriptionIdAssignRecruiterQueryOptions(
		jobDescriptionId,
		assignRecruiterRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get statuses history
 */
export const getApiJobDescriptionStatus = (
	params?: GetApiJobDescriptionStatusParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/job-description/status`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiJobDescriptionStatusMutationKey = () =>
	["getApiJobDescriptionStatus"] as const;

export const getGetApiJobDescriptionStatusMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiJobDescriptionStatus>>,
		TError,
		GetApiJobDescriptionStatusMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiJobDescriptionStatus>>,
	TError,
	GetApiJobDescriptionStatusMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiJobDescriptionStatusMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiJobDescriptionStatus>>,
		GetApiJobDescriptionStatusMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiJobDescriptionStatus(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiJobDescriptionStatusMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiJobDescriptionStatus>>
>;

export type GetApiJobDescriptionStatusMutationError = ErrorType<unknown>;
export type GetApiJobDescriptionStatusMutationVariables = {
	params?: GetApiJobDescriptionStatusParams;
};

/**
 * @summary Get statuses history
 */
export const useGetApiJobDescriptionStatus = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiJobDescriptionStatus>>,
			TError,
			GetApiJobDescriptionStatusMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiJobDescriptionStatus>>,
	TError,
	GetApiJobDescriptionStatusMutationVariables,
	TContext
> => {
	return useMutation(getGetApiJobDescriptionStatusMutationOptions(options), queryClient);
};
/**
 * @summary Update status
 */
export const putApiJobDescriptionJobDescriptionIdStatus = (
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<void>(
		{ url: `/api/job-description/${jobDescriptionId}/${status}`, method: "PUT", signal },
		options,
	);
};

export const getPutApiJobDescriptionJobDescriptionIdStatusQueryKey = (
	jobDescriptionId: string,
	status: JobDescriptionStatus,
) => {
	return ["PUT", `/api/job-description/${jobDescriptionId}/${status}`] as const;
};

export const getPutApiJobDescriptionJobDescriptionIdStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiJobDescriptionJobDescriptionIdStatusQueryKey(jobDescriptionId, status);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>
	> = ({ signal }) =>
		putApiJobDescriptionJobDescriptionIdStatus(jobDescriptionId, status, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled:
			jobDescriptionId !== null &&
			jobDescriptionId !== undefined &&
			status !== null &&
			status !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiJobDescriptionJobDescriptionIdStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>
>;
export type PutApiJobDescriptionJobDescriptionIdStatusQueryError = ErrorType<unknown>;

export function usePutApiJobDescriptionJobDescriptionIdStatus<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
					TError,
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiJobDescriptionJobDescriptionIdStatus<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
					TError,
					Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiJobDescriptionJobDescriptionIdStatus<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update status
 */

export function usePutApiJobDescriptionJobDescriptionIdStatus<
	TData = Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
	TError = ErrorType<unknown>,
>(
	jobDescriptionId: string,
	status: JobDescriptionStatus,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiJobDescriptionJobDescriptionIdStatus>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiJobDescriptionJobDescriptionIdStatusQueryOptions(
		jobDescriptionId,
		status,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
