/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CandidateCreated,
	CandidateProjection,
	CandidateTagged,
	CandidateTagRemoved,
	CandidateUpdated,
	CreateCandidateRequest,
	GetCandidatesParams,
	ProblemDetails,
	SliceResponseOfCandidateProjection,
	TagRequest,
	UpdateCandidateRequest,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Get candidate
 */
export const getCandidate = (
	candidateId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateProjection>(
		{ url: `/api/recruitment/candidates/${candidateId}`, method: "GET", signal },
		options,
	);
};

export const getGetCandidateMutationKey = () => ["getCandidate"] as const;

export const getGetCandidateMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getCandidate>>,
		TError,
		GetCandidateMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getCandidate>>,
	TError,
	GetCandidateMutationVariables,
	TContext
> => {
	const mutationKey = getGetCandidateMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getCandidate>>,
		GetCandidateMutationVariables
	> = (props) => {
		const { candidateId } = props ?? {};

		return getCandidate(candidateId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCandidateMutationResult = NonNullable<Awaited<ReturnType<typeof getCandidate>>>;

export type GetCandidateMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetCandidateMutationVariables = { candidateId: string };

/**
 * @summary Get candidate
 */
export const useGetCandidate = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getCandidate>>,
			TError,
			GetCandidateMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getCandidate>>,
	TError,
	GetCandidateMutationVariables,
	TContext
> => {
	return useMutation(getGetCandidateMutationOptions(options), queryClient);
};
/**
 * @summary Update candidate
 */
export const updateCandidate = (
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateUpdated>(
		{
			url: `/api/recruitment/candidates/${candidateId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateCandidateRequest,
			signal,
		},
		options,
	);
};

export const getUpdateCandidateQueryKey = (
	candidateId: string,
	updateCandidateRequest?: BodyType<UpdateCandidateRequest>,
) => {
	return ["PUT", `/api/recruitment/candidates/${candidateId}`, updateCandidateRequest] as const;
};

export const getUpdateCandidateQueryOptions = <
	TData = Awaited<ReturnType<typeof updateCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getUpdateCandidateQueryKey(candidateId, updateCandidateRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateCandidate>>> = ({ signal }) =>
		updateCandidate(candidateId, updateCandidateRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: candidateId !== null && candidateId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof updateCandidate>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UpdateCandidateQueryResult = NonNullable<Awaited<ReturnType<typeof updateCandidate>>>;
export type UpdateCandidateQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateCandidate<
	TData = Awaited<ReturnType<typeof updateCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCandidate>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateCandidate>>,
					TError,
					Awaited<ReturnType<typeof updateCandidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateCandidate<
	TData = Awaited<ReturnType<typeof updateCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCandidate>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateCandidate>>,
					TError,
					Awaited<ReturnType<typeof updateCandidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateCandidate<
	TData = Awaited<ReturnType<typeof updateCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update candidate
 */

export function useUpdateCandidate<
	TData = Awaited<ReturnType<typeof updateCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateCandidateQueryOptions(candidateId, updateCandidateRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Create candidate
 */
export const createCandidate = (
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateCreated>(
		{
			url: `/api/recruitment/candidates`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createCandidateRequest,
			signal,
		},
		options,
	);
};

export const getCreateCandidateQueryKey = (
	createCandidateRequest?: BodyType<CreateCandidateRequest>,
) => {
	return ["POST", `/api/recruitment/candidates`, createCandidateRequest] as const;
};

export const getCreateCandidateQueryOptions = <
	TData = Awaited<ReturnType<typeof createCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCreateCandidateQueryKey(createCandidateRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof createCandidate>>> = ({ signal }) =>
		createCandidate(createCandidateRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof createCandidate>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateCandidateQueryResult = NonNullable<Awaited<ReturnType<typeof createCandidate>>>;
export type CreateCandidateQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCreateCandidate<
	TData = Awaited<ReturnType<typeof createCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof createCandidate>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof createCandidate>>,
					TError,
					Awaited<ReturnType<typeof createCandidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateCandidate<
	TData = Awaited<ReturnType<typeof createCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createCandidate>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof createCandidate>>,
					TError,
					Awaited<ReturnType<typeof createCandidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateCandidate<
	TData = Awaited<ReturnType<typeof createCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create candidate
 */

export function useCreateCandidate<
	TData = Awaited<ReturnType<typeof createCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCreateCandidateQueryOptions(createCandidateRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get candidates
 */
export const getCandidates = (
	params?: GetCandidatesParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfCandidateProjection>(
		{ url: `/api/recruitment/candidates`, method: "GET", params, signal },
		options,
	);
};

export const getGetCandidatesMutationKey = () => ["getCandidates"] as const;

export const getGetCandidatesMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getCandidates>>,
		TError,
		GetCandidatesMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getCandidates>>,
	TError,
	GetCandidatesMutationVariables,
	TContext
> => {
	const mutationKey = getGetCandidatesMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getCandidates>>,
		GetCandidatesMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getCandidates(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCandidatesMutationResult = NonNullable<Awaited<ReturnType<typeof getCandidates>>>;

export type GetCandidatesMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetCandidatesMutationVariables = { params?: GetCandidatesParams };

/**
 * @summary Get candidates
 */
export const useGetCandidates = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getCandidates>>,
			TError,
			GetCandidatesMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getCandidates>>,
	TError,
	GetCandidatesMutationVariables,
	TContext
> => {
	return useMutation(getGetCandidatesMutationOptions(options), queryClient);
};
/**
 * @summary Tag candidate
 */
export const tagCandidate = (
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateTagged>(
		{
			url: `/api/recruitment/candidates/${candidateId}/tag`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: tagRequest,
			signal,
		},
		options,
	);
};

export const getTagCandidateQueryKey = (candidateId: string, tagRequest?: BodyType<TagRequest>) => {
	return ["PUT", `/api/recruitment/candidates/${candidateId}/tag`, tagRequest] as const;
};

export const getTagCandidateQueryOptions = <
	TData = Awaited<ReturnType<typeof tagCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getTagCandidateQueryKey(candidateId, tagRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof tagCandidate>>> = ({ signal }) =>
		tagCandidate(candidateId, tagRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: candidateId !== null && candidateId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof tagCandidate>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type TagCandidateQueryResult = NonNullable<Awaited<ReturnType<typeof tagCandidate>>>;
export type TagCandidateQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useTagCandidate<
	TData = Awaited<ReturnType<typeof tagCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagCandidate>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof tagCandidate>>,
					TError,
					Awaited<ReturnType<typeof tagCandidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTagCandidate<
	TData = Awaited<ReturnType<typeof tagCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagCandidate>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof tagCandidate>>,
					TError,
					Awaited<ReturnType<typeof tagCandidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTagCandidate<
	TData = Awaited<ReturnType<typeof tagCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Tag candidate
 */

export function useTagCandidate<
	TData = Awaited<ReturnType<typeof tagCandidate>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagCandidate>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getTagCandidateQueryOptions(candidateId, tagRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Remove tag
 */
export const removeCandidateTag = (
	candidateId: string,
	tagId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateTagRemoved>(
		{ url: `/api/recruitment/candidates/${candidateId}/tag/${tagId}`, method: "DELETE", signal },
		options,
	);
};

export const getRemoveCandidateTagQueryKey = (candidateId: string, tagId: string) => {
	return ["DELETE", `/api/recruitment/candidates/${candidateId}/tag/${tagId}`] as const;
};

export const getRemoveCandidateTagQueryOptions = <
	TData = Awaited<ReturnType<typeof removeCandidateTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeCandidateTag>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRemoveCandidateTagQueryKey(candidateId, tagId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof removeCandidateTag>>> = ({ signal }) =>
		removeCandidateTag(candidateId, tagId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled:
			candidateId !== null && candidateId !== undefined && tagId !== null && tagId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof removeCandidateTag>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type RemoveCandidateTagQueryResult = NonNullable<
	Awaited<ReturnType<typeof removeCandidateTag>>
>;
export type RemoveCandidateTagQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useRemoveCandidateTag<
	TData = Awaited<ReturnType<typeof removeCandidateTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagId: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeCandidateTag>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof removeCandidateTag>>,
					TError,
					Awaited<ReturnType<typeof removeCandidateTag>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveCandidateTag<
	TData = Awaited<ReturnType<typeof removeCandidateTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof removeCandidateTag>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof removeCandidateTag>>,
					TError,
					Awaited<ReturnType<typeof removeCandidateTag>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveCandidateTag<
	TData = Awaited<ReturnType<typeof removeCandidateTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeCandidateTag>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Remove tag
 */

export function useRemoveCandidateTag<
	TData = Awaited<ReturnType<typeof removeCandidateTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeCandidateTag>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getRemoveCandidateTagQueryOptions(candidateId, tagId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
