/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CandidateCreated,
	CandidateProjection,
	CandidateTagged,
	CandidateTagRemoved,
	CandidateUpdated,
	CreateCandidateRequest,
	GetApiRecruitmentCandidatesParams,
	ProblemDetails,
	SliceResponseOfCandidateProjection,
	TagRequest,
	UpdateCandidateRequest,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator";
import { customInstance } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Get candidate
 */
export const getApiRecruitmentCandidatesCandidateId = (
	candidateId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateProjection>(
		{ url: `/api/recruitment/candidates/${candidateId}`, method: "GET", signal },
		options,
	);
};

export const getGetApiRecruitmentCandidatesCandidateIdMutationKey = () =>
	["getApiRecruitmentCandidatesCandidateId"] as const;

export const getGetApiRecruitmentCandidatesCandidateIdMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiRecruitmentCandidatesCandidateId>>,
		TError,
		GetApiRecruitmentCandidatesCandidateIdMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiRecruitmentCandidatesCandidateId>>,
	TError,
	GetApiRecruitmentCandidatesCandidateIdMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiRecruitmentCandidatesCandidateIdMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiRecruitmentCandidatesCandidateId>>,
		GetApiRecruitmentCandidatesCandidateIdMutationVariables
	> = (props) => {
		const { candidateId } = props ?? {};

		return getApiRecruitmentCandidatesCandidateId(candidateId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiRecruitmentCandidatesCandidateIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiRecruitmentCandidatesCandidateId>>
>;

export type GetApiRecruitmentCandidatesCandidateIdMutationError = ErrorType<
	BadRequestDetails | ProblemDetails
>;
export type GetApiRecruitmentCandidatesCandidateIdMutationVariables = { candidateId: string };

/**
 * @summary Get candidate
 */
export const useGetApiRecruitmentCandidatesCandidateId = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiRecruitmentCandidatesCandidateId>>,
			TError,
			GetApiRecruitmentCandidatesCandidateIdMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiRecruitmentCandidatesCandidateId>>,
	TError,
	GetApiRecruitmentCandidatesCandidateIdMutationVariables,
	TContext
> => {
	return useMutation(
		getGetApiRecruitmentCandidatesCandidateIdMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Update candidate
 */
export const putApiRecruitmentCandidatesCandidateId = (
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateUpdated>(
		{
			url: `/api/recruitment/candidates/${candidateId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateCandidateRequest,
			signal,
		},
		options,
	);
};

export const getPutApiRecruitmentCandidatesCandidateIdQueryKey = (
	candidateId: string,
	updateCandidateRequest?: BodyType<UpdateCandidateRequest>,
) => {
	return ["PUT", `/api/recruitment/candidates/${candidateId}`, updateCandidateRequest] as const;
};

export const getPutApiRecruitmentCandidatesCandidateIdQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
	TError = ErrorType<unknown>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiRecruitmentCandidatesCandidateIdQueryKey(candidateId, updateCandidateRequest);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>
	> = ({ signal }) =>
		putApiRecruitmentCandidatesCandidateId(
			candidateId,
			updateCandidateRequest,
			requestOptions,
			signal,
		);

	return {
		queryKey,
		queryFn,
		enabled: candidateId !== null && candidateId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiRecruitmentCandidatesCandidateIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>
>;
export type PutApiRecruitmentCandidatesCandidateIdQueryError = ErrorType<unknown>;

export function usePutApiRecruitmentCandidatesCandidateId<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
	TError = ErrorType<unknown>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
					TError,
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiRecruitmentCandidatesCandidateId<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
	TError = ErrorType<unknown>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
					TError,
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiRecruitmentCandidatesCandidateId<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
	TError = ErrorType<unknown>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update candidate
 */

export function usePutApiRecruitmentCandidatesCandidateId<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
	TError = ErrorType<unknown>,
>(
	candidateId: string,
	updateCandidateRequest: BodyType<UpdateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiRecruitmentCandidatesCandidateIdQueryOptions(
		candidateId,
		updateCandidateRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Create candidate
 */
export const postApiRecruitmentCandidates = (
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateCreated>(
		{
			url: `/api/recruitment/candidates`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createCandidateRequest,
			signal,
		},
		options,
	);
};

export const getPostApiRecruitmentCandidatesQueryKey = (
	createCandidateRequest?: BodyType<CreateCandidateRequest>,
) => {
	return ["POST", `/api/recruitment/candidates`, createCandidateRequest] as const;
};

export const getPostApiRecruitmentCandidatesQueryOptions = <
	TData = Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
	TError = ErrorType<BadRequestDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiRecruitmentCandidates>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getPostApiRecruitmentCandidatesQueryKey(createCandidateRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiRecruitmentCandidates>>> = ({
		signal,
	}) => postApiRecruitmentCandidates(createCandidateRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostApiRecruitmentCandidatesQueryResult = NonNullable<
	Awaited<ReturnType<typeof postApiRecruitmentCandidates>>
>;
export type PostApiRecruitmentCandidatesQueryError = ErrorType<BadRequestDetails>;

export function usePostApiRecruitmentCandidates<
	TData = Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
	TError = ErrorType<BadRequestDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiRecruitmentCandidates>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
					TError,
					Awaited<ReturnType<typeof postApiRecruitmentCandidates>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiRecruitmentCandidates<
	TData = Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
	TError = ErrorType<BadRequestDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiRecruitmentCandidates>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
					TError,
					Awaited<ReturnType<typeof postApiRecruitmentCandidates>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostApiRecruitmentCandidates<
	TData = Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
	TError = ErrorType<BadRequestDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiRecruitmentCandidates>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create candidate
 */

export function usePostApiRecruitmentCandidates<
	TData = Awaited<ReturnType<typeof postApiRecruitmentCandidates>>,
	TError = ErrorType<BadRequestDetails>,
>(
	createCandidateRequest: BodyType<CreateCandidateRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof postApiRecruitmentCandidates>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPostApiRecruitmentCandidatesQueryOptions(createCandidateRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get candidates
 */
export const getApiRecruitmentCandidates = (
	params?: GetApiRecruitmentCandidatesParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfCandidateProjection>(
		{ url: `/api/recruitment/candidates`, method: "GET", params, signal },
		options,
	);
};

export const getGetApiRecruitmentCandidatesMutationKey = () =>
	["getApiRecruitmentCandidates"] as const;

export const getGetApiRecruitmentCandidatesMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getApiRecruitmentCandidates>>,
		TError,
		GetApiRecruitmentCandidatesMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getApiRecruitmentCandidates>>,
	TError,
	GetApiRecruitmentCandidatesMutationVariables,
	TContext
> => {
	const mutationKey = getGetApiRecruitmentCandidatesMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getApiRecruitmentCandidates>>,
		GetApiRecruitmentCandidatesMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getApiRecruitmentCandidates(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetApiRecruitmentCandidatesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getApiRecruitmentCandidates>>
>;

export type GetApiRecruitmentCandidatesMutationError = ErrorType<unknown>;
export type GetApiRecruitmentCandidatesMutationVariables = {
	params?: GetApiRecruitmentCandidatesParams;
};

/**
 * @summary Get candidates
 */
export const useGetApiRecruitmentCandidates = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getApiRecruitmentCandidates>>,
			TError,
			GetApiRecruitmentCandidatesMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getApiRecruitmentCandidates>>,
	TError,
	GetApiRecruitmentCandidatesMutationVariables,
	TContext
> => {
	return useMutation(getGetApiRecruitmentCandidatesMutationOptions(options), queryClient);
};
/**
 * @summary Tag candidate
 */
export const putApiRecruitmentCandidatesCandidateIdTag = (
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateTagged>(
		{
			url: `/api/recruitment/candidates/${candidateId}/tag`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: tagRequest,
			signal,
		},
		options,
	);
};

export const getPutApiRecruitmentCandidatesCandidateIdTagQueryKey = (
	candidateId: string,
	tagRequest?: BodyType<TagRequest>,
) => {
	return ["PUT", `/api/recruitment/candidates/${candidateId}/tag`, tagRequest] as const;
};

export const getPutApiRecruitmentCandidatesCandidateIdTagQueryOptions = <
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPutApiRecruitmentCandidatesCandidateIdTagQueryKey(candidateId, tagRequest);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>
	> = ({ signal }) =>
		putApiRecruitmentCandidatesCandidateIdTag(candidateId, tagRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: candidateId !== null && candidateId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PutApiRecruitmentCandidatesCandidateIdTagQueryResult = NonNullable<
	Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>
>;
export type PutApiRecruitmentCandidatesCandidateIdTagQueryError = ErrorType<
	BadRequestDetails | ProblemDetails
>;

export function usePutApiRecruitmentCandidatesCandidateIdTag<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
					TError,
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiRecruitmentCandidatesCandidateIdTag<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
					TError,
					Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePutApiRecruitmentCandidatesCandidateIdTag<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Tag candidate
 */

export function usePutApiRecruitmentCandidatesCandidateIdTag<
	TData = Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	candidateId: string,
	tagRequest: BodyType<TagRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof putApiRecruitmentCandidatesCandidateIdTag>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getPutApiRecruitmentCandidatesCandidateIdTagQueryOptions(
		candidateId,
		tagRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Remove tag
 */
export const deleteApiRecruitmentCandidatesCandidateIdTagTagId = (
	candidateId: string,
	tagId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CandidateTagRemoved>(
		{ url: `/api/recruitment/candidates/${candidateId}/tag/${tagId}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteApiRecruitmentCandidatesCandidateIdTagTagIdQueryKey = (
	candidateId: string,
	tagId: string,
) => {
	return ["DELETE", `/api/recruitment/candidates/${candidateId}/tag/${tagId}`] as const;
};

export const getDeleteApiRecruitmentCandidatesCandidateIdTagTagIdQueryOptions = <
	TData = Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
	TError = ErrorType<BadRequestDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getDeleteApiRecruitmentCandidatesCandidateIdTagTagIdQueryKey(candidateId, tagId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>
	> = ({ signal }) =>
		deleteApiRecruitmentCandidatesCandidateIdTagTagId(candidateId, tagId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled:
			candidateId !== null && candidateId !== undefined && tagId !== null && tagId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DeleteApiRecruitmentCandidatesCandidateIdTagTagIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>
>;
export type DeleteApiRecruitmentCandidatesCandidateIdTagTagIdQueryError =
	ErrorType<BadRequestDetails>;

export function useDeleteApiRecruitmentCandidatesCandidateIdTagTagId<
	TData = Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
	TError = ErrorType<BadRequestDetails>,
>(
	candidateId: string,
	tagId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
					TError,
					Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDeleteApiRecruitmentCandidatesCandidateIdTagTagId<
	TData = Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
	TError = ErrorType<BadRequestDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
					TError,
					Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDeleteApiRecruitmentCandidatesCandidateIdTagTagId<
	TData = Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
	TError = ErrorType<BadRequestDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Remove tag
 */

export function useDeleteApiRecruitmentCandidatesCandidateIdTagTagId<
	TData = Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
	TError = ErrorType<BadRequestDetails>,
>(
	candidateId: string,
	tagId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof deleteApiRecruitmentCandidatesCandidateIdTagTagId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getDeleteApiRecruitmentCandidatesCandidateIdTagTagIdQueryOptions(
		candidateId,
		tagId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
