<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Marten" />
    <PackageReference Include="Marten.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Marten" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailTemplates\HrAgencySystem.EmailTemplates.Contracts\HrAgencySystem.EmailTemplates.Contracts.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Feeds\HrAgencySystem.Feeds.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Files\HrAgencySystem.Files.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Recruitment.Contracts\HrAgencySystem.Recruitment.Contracts.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Reports.ReadModel\HrAgencySystem.Reports.ReadModel.csproj" />
    <ProjectReference Include="..\HrAgencySystem.SharedKernel\HrAgencySystem.SharedKernel.csproj" />
    <ProjectReference Include="..\HrAgencySystem.Workers.Contracts\HrAgencySystem.Workers.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="HrAgencySystem.UnitTests" />
    <InternalsVisibleTo Include="HrAgencySystem.IntegrationTests" />
  </ItemGroup>
</Project>
