/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	AgencyEmploymentEnded,
	AgencyEmploymentProjection,
	AgencyEmploymentStarted,
	AgencyEmploymentTermsChanged,
	BadRequestDetails,
	ChangeAgencyEmploymentTermsRequest,
	EndAgencyEmploymentRequest,
	ListAgencyEmploymentsParams,
	ProblemDetails,
	StartAgencyEmploymentRequest,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator.ts";
import { customInstance } from "../../mutator.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary List employment records
 */
export const listAgencyEmployments = (
	params?: ListAgencyEmploymentsParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgencyEmploymentProjection[]>(
		{ url: `/api/agency-employments`, method: "GET", params, signal },
		options,
	);
};

export const getListAgencyEmploymentsMutationKey = () => ["listAgencyEmployments"] as const;

export const getListAgencyEmploymentsMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof listAgencyEmployments>>,
		TError,
		ListAgencyEmploymentsMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof listAgencyEmployments>>,
	TError,
	ListAgencyEmploymentsMutationVariables,
	TContext
> => {
	const mutationKey = getListAgencyEmploymentsMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof listAgencyEmployments>>,
		ListAgencyEmploymentsMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return listAgencyEmployments(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ListAgencyEmploymentsMutationResult = NonNullable<
	Awaited<ReturnType<typeof listAgencyEmployments>>
>;

export type ListAgencyEmploymentsMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type ListAgencyEmploymentsMutationVariables = { params?: ListAgencyEmploymentsParams };

/**
 * @summary List employment records
 */
export const useListAgencyEmployments = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof listAgencyEmployments>>,
			TError,
			ListAgencyEmploymentsMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof listAgencyEmployments>>,
	TError,
	ListAgencyEmploymentsMutationVariables,
	TContext
> => {
	return useMutation(getListAgencyEmploymentsMutationOptions(options), queryClient);
};
/**
 * @summary Record that somebody works for the agency
 */
export const startAgencyEmployment = (
	startAgencyEmploymentRequest: BodyType<StartAgencyEmploymentRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgencyEmploymentStarted>(
		{
			url: `/api/agency-employments`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: startAgencyEmploymentRequest,
			signal,
		},
		options,
	);
};

export const getStartAgencyEmploymentQueryKey = (
	startAgencyEmploymentRequest?: BodyType<StartAgencyEmploymentRequest>,
) => {
	return ["POST", `/api/agency-employments`, startAgencyEmploymentRequest] as const;
};

export const getStartAgencyEmploymentQueryOptions = <
	TData = Awaited<ReturnType<typeof startAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	startAgencyEmploymentRequest: BodyType<StartAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof startAgencyEmployment>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getStartAgencyEmploymentQueryKey(startAgencyEmploymentRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof startAgencyEmployment>>> = ({ signal }) =>
		startAgencyEmployment(startAgencyEmploymentRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof startAgencyEmployment>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StartAgencyEmploymentQueryResult = NonNullable<
	Awaited<ReturnType<typeof startAgencyEmployment>>
>;
export type StartAgencyEmploymentQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useStartAgencyEmployment<
	TData = Awaited<ReturnType<typeof startAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	startAgencyEmploymentRequest: BodyType<StartAgencyEmploymentRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof startAgencyEmployment>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof startAgencyEmployment>>,
					TError,
					Awaited<ReturnType<typeof startAgencyEmployment>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useStartAgencyEmployment<
	TData = Awaited<ReturnType<typeof startAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	startAgencyEmploymentRequest: BodyType<StartAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof startAgencyEmployment>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof startAgencyEmployment>>,
					TError,
					Awaited<ReturnType<typeof startAgencyEmployment>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useStartAgencyEmployment<
	TData = Awaited<ReturnType<typeof startAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	startAgencyEmploymentRequest: BodyType<StartAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof startAgencyEmployment>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Record that somebody works for the agency
 */

export function useStartAgencyEmployment<
	TData = Awaited<ReturnType<typeof startAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	startAgencyEmploymentRequest: BodyType<StartAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof startAgencyEmployment>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getStartAgencyEmploymentQueryOptions(startAgencyEmploymentRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get somebody's employment record
 */
export const getAgencyEmployment = (
	userId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgencyEmploymentProjection>(
		{ url: `/api/agency-employments/${userId}`, method: "GET", signal },
		options,
	);
};

export const getGetAgencyEmploymentMutationKey = () => ["getAgencyEmployment"] as const;

export const getGetAgencyEmploymentMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getAgencyEmployment>>,
		TError,
		GetAgencyEmploymentMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getAgencyEmployment>>,
	TError,
	GetAgencyEmploymentMutationVariables,
	TContext
> => {
	const mutationKey = getGetAgencyEmploymentMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getAgencyEmployment>>,
		GetAgencyEmploymentMutationVariables
	> = (props) => {
		const { userId } = props ?? {};

		return getAgencyEmployment(userId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetAgencyEmploymentMutationResult = NonNullable<
	Awaited<ReturnType<typeof getAgencyEmployment>>
>;

export type GetAgencyEmploymentMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetAgencyEmploymentMutationVariables = { userId: string };

/**
 * @summary Get somebody's employment record
 */
export const useGetAgencyEmployment = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getAgencyEmployment>>,
			TError,
			GetAgencyEmploymentMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getAgencyEmployment>>,
	TError,
	GetAgencyEmploymentMutationVariables,
	TContext
> => {
	return useMutation(getGetAgencyEmploymentMutationOptions(options), queryClient);
};
/**
 * @summary Change the terms somebody works on
 */
export const changeAgencyEmploymentTerms = (
	userId: string,
	changeAgencyEmploymentTermsRequest: BodyType<ChangeAgencyEmploymentTermsRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgencyEmploymentTermsChanged>(
		{
			url: `/api/agency-employments/${userId}/terms`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: changeAgencyEmploymentTermsRequest,
			signal,
		},
		options,
	);
};

export const getChangeAgencyEmploymentTermsQueryKey = (
	userId: string,
	changeAgencyEmploymentTermsRequest?: BodyType<ChangeAgencyEmploymentTermsRequest>,
) => {
	return [
		"PUT",
		`/api/agency-employments/${userId}/terms`,
		changeAgencyEmploymentTermsRequest,
	] as const;
};

export const getChangeAgencyEmploymentTermsQueryOptions = <
	TData = Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeAgencyEmploymentTermsRequest: BodyType<ChangeAgencyEmploymentTermsRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getChangeAgencyEmploymentTermsQueryKey(userId, changeAgencyEmploymentTermsRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>> = ({
		signal,
	}) =>
		changeAgencyEmploymentTerms(userId, changeAgencyEmploymentTermsRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: userId !== null && userId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ChangeAgencyEmploymentTermsQueryResult = NonNullable<
	Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>
>;
export type ChangeAgencyEmploymentTermsQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useChangeAgencyEmploymentTerms<
	TData = Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeAgencyEmploymentTermsRequest: BodyType<ChangeAgencyEmploymentTermsRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
					TError,
					Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeAgencyEmploymentTerms<
	TData = Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeAgencyEmploymentTermsRequest: BodyType<ChangeAgencyEmploymentTermsRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
					TError,
					Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangeAgencyEmploymentTerms<
	TData = Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeAgencyEmploymentTermsRequest: BodyType<ChangeAgencyEmploymentTermsRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change the terms somebody works on
 */

export function useChangeAgencyEmploymentTerms<
	TData = Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	changeAgencyEmploymentTermsRequest: BodyType<ChangeAgencyEmploymentTermsRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof changeAgencyEmploymentTerms>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getChangeAgencyEmploymentTermsQueryOptions(
		userId,
		changeAgencyEmploymentTermsRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary End somebody's engagement
 */
export const endAgencyEmployment = (
	userId: string,
	endAgencyEmploymentRequest: BodyType<EndAgencyEmploymentRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<AgencyEmploymentEnded>(
		{
			url: `/api/agency-employments/${userId}/end`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: endAgencyEmploymentRequest,
			signal,
		},
		options,
	);
};

export const getEndAgencyEmploymentQueryKey = (
	userId: string,
	endAgencyEmploymentRequest?: BodyType<EndAgencyEmploymentRequest>,
) => {
	return ["POST", `/api/agency-employments/${userId}/end`, endAgencyEmploymentRequest] as const;
};

export const getEndAgencyEmploymentQueryOptions = <
	TData = Awaited<ReturnType<typeof endAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	endAgencyEmploymentRequest: BodyType<EndAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof endAgencyEmployment>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getEndAgencyEmploymentQueryKey(userId, endAgencyEmploymentRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof endAgencyEmployment>>> = ({ signal }) =>
		endAgencyEmployment(userId, endAgencyEmploymentRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: userId !== null && userId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof endAgencyEmployment>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type EndAgencyEmploymentQueryResult = NonNullable<
	Awaited<ReturnType<typeof endAgencyEmployment>>
>;
export type EndAgencyEmploymentQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useEndAgencyEmployment<
	TData = Awaited<ReturnType<typeof endAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	endAgencyEmploymentRequest: BodyType<EndAgencyEmploymentRequest>,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof endAgencyEmployment>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof endAgencyEmployment>>,
					TError,
					Awaited<ReturnType<typeof endAgencyEmployment>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEndAgencyEmployment<
	TData = Awaited<ReturnType<typeof endAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	endAgencyEmploymentRequest: BodyType<EndAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof endAgencyEmployment>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof endAgencyEmployment>>,
					TError,
					Awaited<ReturnType<typeof endAgencyEmployment>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEndAgencyEmployment<
	TData = Awaited<ReturnType<typeof endAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	endAgencyEmploymentRequest: BodyType<EndAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof endAgencyEmployment>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary End somebody's engagement
 */

export function useEndAgencyEmployment<
	TData = Awaited<ReturnType<typeof endAgencyEmployment>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	userId: string,
	endAgencyEmploymentRequest: BodyType<EndAgencyEmploymentRequest>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof endAgencyEmployment>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getEndAgencyEmploymentQueryOptions(
		userId,
		endAgencyEmploymentRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
