/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CreateTaskRequest,
	GetTaskBoardParams,
	ProblemDetails,
	TaskBoard,
	TaskItemCompleted,
	TaskItemCreated,
	TaskItemProjection,
	TaskItemReopened,
	TaskItemUpdated,
	UpdateTaskRequest,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator.ts";
import { customInstance } from "../../mutator.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * Open tasks due before the end of the range, overdue ones included, and tasks done within it. The range is worked out in the given IANA time zone (Europe/Warsaw when left out).
 * @summary Get my tasks for a day, a week or a month
 */
export const getTaskBoard = (
	params?: GetTaskBoardParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<TaskBoard>({ url: `/api/tasks`, method: "GET", params, signal }, options);
};

export const getGetTaskBoardMutationKey = () => ["getTaskBoard"] as const;

export const getGetTaskBoardMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getTaskBoard>>,
		TError,
		GetTaskBoardMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getTaskBoard>>,
	TError,
	GetTaskBoardMutationVariables,
	TContext
> => {
	const mutationKey = getGetTaskBoardMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getTaskBoard>>,
		GetTaskBoardMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getTaskBoard(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetTaskBoardMutationResult = NonNullable<Awaited<ReturnType<typeof getTaskBoard>>>;

export type GetTaskBoardMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetTaskBoardMutationVariables = { params?: GetTaskBoardParams };

/**
 * @summary Get my tasks for a day, a week or a month
 */
export const useGetTaskBoard = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getTaskBoard>>,
			TError,
			GetTaskBoardMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getTaskBoard>>,
	TError,
	GetTaskBoardMutationVariables,
	TContext
> => {
	return useMutation(getGetTaskBoardMutationOptions(options), queryClient);
};
/**
 * @summary Create a task
 */
export const createTask = (
	createTaskRequest: BodyType<CreateTaskRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<TaskItemCreated>(
		{
			url: `/api/tasks`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createTaskRequest,
			signal,
		},
		options,
	);
};

export const getCreateTaskQueryKey = (createTaskRequest?: BodyType<CreateTaskRequest>) => {
	return ["POST", `/api/tasks`, createTaskRequest] as const;
};

export const getCreateTaskQueryOptions = <
	TData = Awaited<ReturnType<typeof createTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createTaskRequest: BodyType<CreateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCreateTaskQueryKey(createTaskRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof createTask>>> = ({ signal }) =>
		createTask(createTaskRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof createTask>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateTaskQueryResult = NonNullable<Awaited<ReturnType<typeof createTask>>>;
export type CreateTaskQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCreateTask<
	TData = Awaited<ReturnType<typeof createTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createTaskRequest: BodyType<CreateTaskRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof createTask>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof createTask>>,
					TError,
					Awaited<ReturnType<typeof createTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateTask<
	TData = Awaited<ReturnType<typeof createTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createTaskRequest: BodyType<CreateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createTask>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof createTask>>,
					TError,
					Awaited<ReturnType<typeof createTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateTask<
	TData = Awaited<ReturnType<typeof createTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createTaskRequest: BodyType<CreateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create a task
 */

export function useCreateTask<
	TData = Awaited<ReturnType<typeof createTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	createTaskRequest: BodyType<CreateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCreateTaskQueryOptions(createTaskRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get a task
 */
export const getTask = (
	taskId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<TaskItemProjection>(
		{ url: `/api/tasks/${taskId}`, method: "GET", signal },
		options,
	);
};

export const getGetTaskMutationKey = () => ["getTask"] as const;

export const getGetTaskMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getTask>>,
		TError,
		GetTaskMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getTask>>,
	TError,
	GetTaskMutationVariables,
	TContext
> => {
	const mutationKey = getGetTaskMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getTask>>,
		GetTaskMutationVariables
	> = (props) => {
		const { taskId } = props ?? {};

		return getTask(taskId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetTaskMutationResult = NonNullable<Awaited<ReturnType<typeof getTask>>>;

export type GetTaskMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetTaskMutationVariables = { taskId: string };

/**
 * @summary Get a task
 */
export const useGetTask = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getTask>>,
			TError,
			GetTaskMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getTask>>,
	TError,
	GetTaskMutationVariables,
	TContext
> => {
	return useMutation(getGetTaskMutationOptions(options), queryClient);
};
/**
 * @summary Change an open task
 */
export const updateTask = (
	taskId: string,
	updateTaskRequest: BodyType<UpdateTaskRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<TaskItemUpdated>(
		{
			url: `/api/tasks/${taskId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateTaskRequest,
			signal,
		},
		options,
	);
};

export const getUpdateTaskQueryKey = (
	taskId: string,
	updateTaskRequest?: BodyType<UpdateTaskRequest>,
) => {
	return ["PUT", `/api/tasks/${taskId}`, updateTaskRequest] as const;
};

export const getUpdateTaskQueryOptions = <
	TData = Awaited<ReturnType<typeof updateTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	updateTaskRequest: BodyType<UpdateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUpdateTaskQueryKey(taskId, updateTaskRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateTask>>> = ({ signal }) =>
		updateTask(taskId, updateTaskRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: taskId !== null && taskId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof updateTask>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UpdateTaskQueryResult = NonNullable<Awaited<ReturnType<typeof updateTask>>>;
export type UpdateTaskQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateTask<
	TData = Awaited<ReturnType<typeof updateTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	updateTaskRequest: BodyType<UpdateTaskRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTask>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateTask>>,
					TError,
					Awaited<ReturnType<typeof updateTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateTask<
	TData = Awaited<ReturnType<typeof updateTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	updateTaskRequest: BodyType<UpdateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTask>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateTask>>,
					TError,
					Awaited<ReturnType<typeof updateTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateTask<
	TData = Awaited<ReturnType<typeof updateTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	updateTaskRequest: BodyType<UpdateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change an open task
 */

export function useUpdateTask<
	TData = Awaited<ReturnType<typeof updateTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	updateTaskRequest: BodyType<UpdateTaskRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateTaskQueryOptions(taskId, updateTaskRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Mark a task as done
 */
export const completeTask = (
	taskId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<TaskItemCompleted>(
		{ url: `/api/tasks/${taskId}/complete`, method: "POST", signal },
		options,
	);
};

export const getCompleteTaskQueryKey = (taskId: string) => {
	return ["POST", `/api/tasks/${taskId}/complete`] as const;
};

export const getCompleteTaskQueryOptions = <
	TData = Awaited<ReturnType<typeof completeTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completeTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCompleteTaskQueryKey(taskId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof completeTask>>> = ({ signal }) =>
		completeTask(taskId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: taskId !== null && taskId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof completeTask>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type CompleteTaskQueryResult = NonNullable<Awaited<ReturnType<typeof completeTask>>>;
export type CompleteTaskQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCompleteTask<
	TData = Awaited<ReturnType<typeof completeTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof completeTask>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof completeTask>>,
					TError,
					Awaited<ReturnType<typeof completeTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCompleteTask<
	TData = Awaited<ReturnType<typeof completeTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completeTask>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof completeTask>>,
					TError,
					Awaited<ReturnType<typeof completeTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCompleteTask<
	TData = Awaited<ReturnType<typeof completeTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completeTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Mark a task as done
 */

export function useCompleteTask<
	TData = Awaited<ReturnType<typeof completeTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof completeTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCompleteTaskQueryOptions(taskId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Take a done task back to open
 */
export const reopenTask = (
	taskId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<TaskItemReopened>(
		{ url: `/api/tasks/${taskId}/reopen`, method: "POST", signal },
		options,
	);
};

export const getReopenTaskQueryKey = (taskId: string) => {
	return ["POST", `/api/tasks/${taskId}/reopen`] as const;
};

export const getReopenTaskQueryOptions = <
	TData = Awaited<ReturnType<typeof reopenTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reopenTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getReopenTaskQueryKey(taskId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof reopenTask>>> = ({ signal }) =>
		reopenTask(taskId, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: taskId !== null && taskId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof reopenTask>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ReopenTaskQueryResult = NonNullable<Awaited<ReturnType<typeof reopenTask>>>;
export type ReopenTaskQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useReopenTask<
	TData = Awaited<ReturnType<typeof reopenTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof reopenTask>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof reopenTask>>,
					TError,
					Awaited<ReturnType<typeof reopenTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useReopenTask<
	TData = Awaited<ReturnType<typeof reopenTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reopenTask>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof reopenTask>>,
					TError,
					Awaited<ReturnType<typeof reopenTask>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useReopenTask<
	TData = Awaited<ReturnType<typeof reopenTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reopenTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Take a done task back to open
 */

export function useReopenTask<
	TData = Awaited<ReturnType<typeof reopenTask>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	taskId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reopenTask>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getReopenTaskQueryOptions(taskId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
