/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HR Agency System
 * REST API for managing recruitment agency operations.
 *
 * The API provides functionality for:
 * - organization and user management
 * - sales opportunities and activities
 * - companies and contacts
 * - job descriptions and job postings
 * - candidates and job applications
 * - schedule interviews
 * OpenAPI spec version: v1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	BadRequestDetails,
	CloseLegalEntityRequest,
	GetLegalEntitiesParams,
	LegalEntityClosed,
	LegalEntityCreated,
	LegalEntityProjection,
	LegalEntityRequest,
	LegalEntityUpdated,
	ProblemDetails,
	SliceResponseOfLegalEntityProjection,
} from "../../models";
import type { BodyType, ErrorType } from "../../mutator.ts";
import { customInstance } from "../../mutator.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * @summary Create legal entity
 */
export const createLegalEntity = (
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<LegalEntityCreated>(
		{
			url: `/api/legal-entities`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: legalEntityRequest,
			signal,
		},
		options,
	);
};

export const getCreateLegalEntityQueryKey = (legalEntityRequest?: BodyType<LegalEntityRequest>) => {
	return ["POST", `/api/legal-entities`, legalEntityRequest] as const;
};

export const getCreateLegalEntityQueryOptions = <
	TData = Awaited<ReturnType<typeof createLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCreateLegalEntityQueryKey(legalEntityRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof createLegalEntity>>> = ({ signal }) =>
		createLegalEntity(legalEntityRequest, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof createLegalEntity>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateLegalEntityQueryResult = NonNullable<
	Awaited<ReturnType<typeof createLegalEntity>>
>;
export type CreateLegalEntityQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCreateLegalEntity<
	TData = Awaited<ReturnType<typeof createLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof createLegalEntity>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof createLegalEntity>>,
					TError,
					Awaited<ReturnType<typeof createLegalEntity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateLegalEntity<
	TData = Awaited<ReturnType<typeof createLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createLegalEntity>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof createLegalEntity>>,
					TError,
					Awaited<ReturnType<typeof createLegalEntity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateLegalEntity<
	TData = Awaited<ReturnType<typeof createLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create legal entity
 */

export function useCreateLegalEntity<
	TData = Awaited<ReturnType<typeof createLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCreateLegalEntityQueryOptions(legalEntityRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get legal entities
 */
export const getLegalEntities = (
	params?: GetLegalEntitiesParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<SliceResponseOfLegalEntityProjection>(
		{ url: `/api/legal-entities`, method: "GET", params, signal },
		options,
	);
};

export const getGetLegalEntitiesMutationKey = () => ["getLegalEntities"] as const;

export const getGetLegalEntitiesMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getLegalEntities>>,
		TError,
		GetLegalEntitiesMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getLegalEntities>>,
	TError,
	GetLegalEntitiesMutationVariables,
	TContext
> => {
	const mutationKey = getGetLegalEntitiesMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getLegalEntities>>,
		GetLegalEntitiesMutationVariables
	> = (props) => {
		const { params } = props ?? {};

		return getLegalEntities(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetLegalEntitiesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getLegalEntities>>
>;

export type GetLegalEntitiesMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetLegalEntitiesMutationVariables = { params?: GetLegalEntitiesParams };

/**
 * @summary Get legal entities
 */
export const useGetLegalEntities = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getLegalEntities>>,
			TError,
			GetLegalEntitiesMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getLegalEntities>>,
	TError,
	GetLegalEntitiesMutationVariables,
	TContext
> => {
	return useMutation(getGetLegalEntitiesMutationOptions(options), queryClient);
};
/**
 * @summary Update legal entity
 */
export const updateLegalEntity = (
	legalEntityId: string,
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<LegalEntityUpdated>(
		{
			url: `/api/legal-entities/${legalEntityId}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: legalEntityRequest,
			signal,
		},
		options,
	);
};

export const getUpdateLegalEntityQueryKey = (
	legalEntityId: string,
	legalEntityRequest?: BodyType<LegalEntityRequest>,
) => {
	return ["PUT", `/api/legal-entities/${legalEntityId}`, legalEntityRequest] as const;
};

export const getUpdateLegalEntityQueryOptions = <
	TData = Awaited<ReturnType<typeof updateLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getUpdateLegalEntityQueryKey(legalEntityId, legalEntityRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof updateLegalEntity>>> = ({ signal }) =>
		updateLegalEntity(legalEntityId, legalEntityRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: legalEntityId !== null && legalEntityId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof updateLegalEntity>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UpdateLegalEntityQueryResult = NonNullable<
	Awaited<ReturnType<typeof updateLegalEntity>>
>;
export type UpdateLegalEntityQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useUpdateLegalEntity<
	TData = Awaited<ReturnType<typeof updateLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLegalEntity>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateLegalEntity>>,
					TError,
					Awaited<ReturnType<typeof updateLegalEntity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateLegalEntity<
	TData = Awaited<ReturnType<typeof updateLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLegalEntity>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateLegalEntity>>,
					TError,
					Awaited<ReturnType<typeof updateLegalEntity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateLegalEntity<
	TData = Awaited<ReturnType<typeof updateLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update legal entity
 */

export function useUpdateLegalEntity<
	TData = Awaited<ReturnType<typeof updateLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	legalEntityRequest: BodyType<LegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUpdateLegalEntityQueryOptions(legalEntityId, legalEntityRequest, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get legal entity
 */
export const getLegalEntity = (
	legalEntityId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<LegalEntityProjection>(
		{ url: `/api/legal-entities/${legalEntityId}`, method: "GET", signal },
		options,
	);
};

export const getGetLegalEntityMutationKey = () => ["getLegalEntity"] as const;

export const getGetLegalEntityMutationOptions = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getLegalEntity>>,
		TError,
		GetLegalEntityMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getLegalEntity>>,
	TError,
	GetLegalEntityMutationVariables,
	TContext
> => {
	const mutationKey = getGetLegalEntityMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getLegalEntity>>,
		GetLegalEntityMutationVariables
	> = (props) => {
		const { legalEntityId } = props ?? {};

		return getLegalEntity(legalEntityId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetLegalEntityMutationResult = NonNullable<Awaited<ReturnType<typeof getLegalEntity>>>;

export type GetLegalEntityMutationError = ErrorType<BadRequestDetails | ProblemDetails>;
export type GetLegalEntityMutationVariables = { legalEntityId: string };

/**
 * @summary Get legal entity
 */
export const useGetLegalEntity = <
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getLegalEntity>>,
			TError,
			GetLegalEntityMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getLegalEntity>>,
	TError,
	GetLegalEntityMutationVariables,
	TContext
> => {
	return useMutation(getGetLegalEntityMutationOptions(options), queryClient);
};
/**
 * @summary Close a legal entity
 */
export const closeLegalEntity = (
	legalEntityId: string,
	closeLegalEntityRequest: BodyType<CloseLegalEntityRequest>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<LegalEntityClosed>(
		{
			url: `/api/legal-entities/${legalEntityId}/close`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: closeLegalEntityRequest,
			signal,
		},
		options,
	);
};

export const getCloseLegalEntityQueryKey = (
	legalEntityId: string,
	closeLegalEntityRequest?: BodyType<CloseLegalEntityRequest>,
) => {
	return ["PUT", `/api/legal-entities/${legalEntityId}/close`, closeLegalEntityRequest] as const;
};

export const getCloseLegalEntityQueryOptions = <
	TData = Awaited<ReturnType<typeof closeLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	closeLegalEntityRequest: BodyType<CloseLegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof closeLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getCloseLegalEntityQueryKey(legalEntityId, closeLegalEntityRequest);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof closeLegalEntity>>> = ({ signal }) =>
		closeLegalEntity(legalEntityId, closeLegalEntityRequest, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: legalEntityId !== null && legalEntityId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof closeLegalEntity>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type CloseLegalEntityQueryResult = NonNullable<Awaited<ReturnType<typeof closeLegalEntity>>>;
export type CloseLegalEntityQueryError = ErrorType<BadRequestDetails | ProblemDetails>;

export function useCloseLegalEntity<
	TData = Awaited<ReturnType<typeof closeLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	closeLegalEntityRequest: BodyType<CloseLegalEntityRequest>,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof closeLegalEntity>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof closeLegalEntity>>,
					TError,
					Awaited<ReturnType<typeof closeLegalEntity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCloseLegalEntity<
	TData = Awaited<ReturnType<typeof closeLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	closeLegalEntityRequest: BodyType<CloseLegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof closeLegalEntity>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof closeLegalEntity>>,
					TError,
					Awaited<ReturnType<typeof closeLegalEntity>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCloseLegalEntity<
	TData = Awaited<ReturnType<typeof closeLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	closeLegalEntityRequest: BodyType<CloseLegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof closeLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Close a legal entity
 */

export function useCloseLegalEntity<
	TData = Awaited<ReturnType<typeof closeLegalEntity>>,
	TError = ErrorType<BadRequestDetails | ProblemDetails>,
>(
	legalEntityId: string,
	closeLegalEntityRequest: BodyType<CloseLegalEntityRequest>,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof closeLegalEntity>>, TError, TData>>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getCloseLegalEntityQueryOptions(
		legalEntityId,
		closeLegalEntityRequest,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
