<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Marten" Version="9.30.0"/>
        <PackageReference Include="WolverineFx" Version="6.30.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HrAgencySystem.Company\HrAgencySystem.Company.csproj"/>
        <ProjectReference Include="..\HrAgencySystem.SharedKernel\HrAgencySystem.SharedKernel.csproj"/>
    </ItemGroup>

</Project>
